"""Trufflepig-surface contracts for reference accessors.

Pirlygenes owns the ID-keyed HPA/pan-cancer matrix and normalization
primitives. Trufflepig owns the deconvolved tumor-only artifacts
generated by its decomposition code. The tests below pin that boundary:

- ``trufflepig.reference.pan_cancer_expression()`` flips
  ``renormalize_to_million`` to True by default (pirlygenes' own
  default is False, so the user RNA-seq path here lands on a true
  TPM-1e6 footing without each caller having to opt in).
- ``tcga_<CODE>`` symbol-joined deconvolution columns are not part of
  the default pan-cancer frame.
- Deconvolved tumor-only references are loaded through explicit
  trufflepig accessors.
"""

import pytest

import trufflepig.reference as gsc


def test_pan_cancer_expression_renormalizes_to_million_by_default():
    """Trufflepig default: every value column should sum to ~1e6 so the
    analysis pipeline can compare user-sample TPM to cohort columns on
    a shared per-million footing."""
    df = gsc.pan_cancer_expression()
    value_cols = [c for c in df.columns if c.endswith(("_TPM", "_nTPM"))]
    assert value_cols, "expected per-tissue / per-cohort value columns"
    for sample_col in (
        next(c for c in value_cols if c.endswith("_TPM")),
        next(c for c in value_cols if c.endswith("_nTPM")),
    ):
        col_sum = float(df[sample_col].astype(float).sum(skipna=True))
        assert col_sum == pytest.approx(1e6, rel=1e-3), (sample_col, col_sum)
    assert any(c.endswith("_TPM_raw") for c in df.columns)
    assert any(c.endswith("_TPM_clean") for c in df.columns)
    assert not any(
        c.startswith(("FPKM_", "TPM_", "nTPM_", "TPM_clean_", "nTPM_clean_"))
        or c.endswith("_FPKM")
        for c in df.columns
    )
    assert not any(c.startswith("tcga_") for c in df.columns)


def test_pan_cancer_clean_values_are_default_and_raw_qc_signal_is_explicit():
    from pirlygenes.gene_sets_cancer import mitochondrial_gene_names

    mt_genes = set(mitochondrial_gene_names())
    df = gsc.pan_cancer_expression()

    mt_rows = df["Symbol"].isin(mt_genes)
    mt_raw = float(df.loc[mt_rows, "COAD_TPM_raw"].sum())
    mt_clean = float(df.loc[mt_rows, "COAD_TPM_clean"].sum())
    mt_alias = float(df.loc[mt_rows, "COAD_TPM"].sum())
    assert mt_raw > 0
    assert mt_clean == pytest.approx(0.0)
    assert mt_alias == pytest.approx(0.0)
    clean_alias = df["COAD_TPM"]
    clean = df["COAD_TPM_clean"]
    assert ((clean_alias == clean) | (clean_alias.isna() & clean.isna())).all()


def test_pan_cancer_wrapper_overrides_pirlygenes_default_to_tpm(monkeypatch):
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()
    calls = []

    def fake_pan_cancer_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [1_000_000.0],
                "PRAD_TPM_clean": [1_000_000.0],
            }
        )

    monkeypatch.setattr(gsc, "_PIRLYGENES_PAN_HAS_NORMALIZE_PRESETS", True)
    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    try:
        gsc.pan_cancer_expression(genes=["KLK3"])
        gsc.pan_cancer_expression(genes=["KLK3"], technical_rna_normalize=True)

        assert calls == [
            {"genes": ("KLK3",), "normalize": ["tpm", "tpm_clean"]},
            {"genes": ("KLK3",), "normalize": ["tpm", "tpm_clean"]},
        ]
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_pan_cancer_expression_rejects_legacy_unit_prefix_columns():
    import pandas as pd

    with pytest.raises(ValueError, match="legacy unit-prefix"):
        gsc._standardize_pan_cancer_columns(
            pd.DataFrame(
                {
                    "Ensembl_Gene_ID": ["ENSG00000142515"],
                    "Symbol": ["KLK3"],
                    "TPM_clean_PRAD": [1.0],
                }
            )
        )


def test_pan_cancer_expression_rejects_native_scale_opt_out():
    with pytest.raises(ValueError, match="normalized TPM-scale"):
        gsc.pan_cancer_expression(renormalize_to_million=False)


def test_pan_cancer_expression_excludes_symbol_joined_deconvolved_columns():
    df = gsc.pan_cancer_expression(genes=["KLK3"])
    tcga_cols = [c for c in df.columns if c.startswith("tcga_")]
    assert tcga_cols == []


def test_pan_cancer_expression_gene_filter_preserves_reference_scale(monkeypatch):
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()

    def fake_pan_cancer_expression(**kwargs):
        assert kwargs["genes"] == ("KLK3",)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [12_345.0],
                "PRAD_TPM_clean": [23_456.0],
            }
        )

    monkeypatch.setattr(gsc, "_PIRLYGENES_PAN_HAS_NORMALIZE_PRESETS", True)
    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    try:
        df = gsc.pan_cancer_expression(genes=["KLK3"])
        assert df.loc[0, "PRAD_TPM_raw"] == pytest.approx(12_345.0)
        assert df.loc[0, "PRAD_TPM_clean"] == pytest.approx(23_456.0)
        assert df.loc[0, "PRAD_TPM"] == pytest.approx(23_456.0)
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_tcga_deconvolved_expression_is_explicit_trufflepig_reference():
    df = gsc.tcga_deconvolved_expression()
    assert {"symbol", "cancer_code", "tumor_tpm_median"}.issubset(df.columns)
    assert "Ensembl_Gene_ID" in df.columns
    assert "PRAD" in set(df["cancer_code"].astype(str))
    mapped = df["Ensembl_Gene_ID"].notna().mean()
    assert mapped > 0.99


def test_tcga_deconvolved_expression_renormalizes_per_group_by_default():
    df = gsc.tcga_deconvolved_expression()
    grp = df.groupby("cancer_code", dropna=False)["tumor_tpm_median"].sum()
    nonzero = grp[grp > 0]
    assert len(nonzero) > 0
    median_sum = float(nonzero.median())
    assert median_sum == pytest.approx(1e6, rel=1e-3), median_sum


def test_deconvolved_renormalization_preserves_quantile_order(monkeypatch):
    import pandas as pd

    fake = pd.DataFrame(
        {
            "Ensembl_Gene_ID": ["ENSG00000142515", "ENSG00000121410"],
            "symbol": ["KLK3", "A1BG"],
            "cancer_code": ["PRAD", "PRAD"],
            "tumor_tpm_q1": [9.0, 1.0],
            "tumor_tpm_median": [10.0, 30.0],
            "tumor_tpm_q3": [11.0, 31.0],
            "n_samples": [2, 2],
        }
    )

    monkeypatch.setattr(
        gsc,
        "_tcga_deconvolved_expression_cached",
        lambda: fake,
    )

    out = gsc.tcga_deconvolved_expression()
    row = out[out["symbol"] == "KLK3"].iloc[0]
    assert row["tumor_tpm_q1"] <= row["tumor_tpm_median"] <= row["tumor_tpm_q3"]
    assert out.groupby("cancer_code")["tumor_tpm_median"].sum().iloc[0] == pytest.approx(
        1_000_000.0
    )


def test_tcga_deconvolved_expression_rejects_native_scale_opt_out():
    with pytest.raises(ValueError, match="normalized TPM-scale"):
        gsc.tcga_deconvolved_expression(renormalize_to_million=False)


def test_matched_normal_marker_panels_are_explicit_trufflepig_references():
    solid = gsc.tumor_up_vs_matched_normal("BRCA")
    heme = gsc.heme_tumor_up_vs_matched_normal("DLBC")

    assert set(solid["cancer_code"]) == {"BRCA"}
    assert {"symbol", "ensembl_gene_id", "tumor_tpm"}.issubset(solid.columns)
    assert set(heme["cancer_code"]) == {"DLBC"}
    assert {"symbol", "ensembl_gene_id", "tumor_tpm"}.issubset(heme.columns)


def test_pan_cancer_expression_cache_returns_defensive_copies(monkeypatch):
    """The trufflepig shim caches transformed frames but callers still
    receive copies they can mutate safely."""
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()
    calls = []

    def fake_pan_cancer_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [1_000_000.0],
                "PRAD_TPM_clean": [1_000_000.0],
            }
        )

    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    try:
        first = gsc.pan_cancer_expression(genes=["klk3"])
        first.loc[0, "PRAD_TPM"] = 99.0
        second = gsc.pan_cancer_expression(genes=["KLK3"])

        assert len(calls) == 1
        assert second.loc[0, "PRAD_TPM"] == 1_000_000.0
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_subtype_deconvolved_expression_renormalizes_per_group_by_default():
    """Trufflepig default: each (cancer_code, subtype) group's
    tumor_tpm_median should sum to ~1e6 so cross-subtype comparisons are
    on a per-million footing."""
    df = gsc.subtype_deconvolved_expression()
    # Pick a well-populated cohort to avoid sparse-subtype edge cases.
    grp = df.groupby(["cancer_code", "subtype"], dropna=False)["tumor_tpm_median"].sum()
    nonzero = grp[grp > 0]
    assert len(nonzero) > 0
    median_sum = float(nonzero.median())
    assert median_sum == pytest.approx(1e6, rel=1e-3), median_sum


def test_subtype_deconvolved_expression_rejects_native_scale_opt_out():
    with pytest.raises(ValueError, match="normalized TPM-scale"):
        gsc.subtype_deconvolved_expression(renormalize_to_million=False)


def test_cancer_expression_uses_trufflepig_reference_surface(monkeypatch):
    """Legacy helper composes trufflepig's pan-cancer wrapper, not the
    upstream pirlygenes default surface."""
    import pandas as pd

    calls = []

    def fake_pan_cancer_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [42.0],
            }
        )

    monkeypatch.setattr(gsc, "pan_cancer_expression", fake_pan_cancer_expression)

    out = gsc.cancer_expression("PRAD", genes=["KLK3"])

    assert calls == [
        {
            "genes": ["KLK3"],
            "normalize": "housekeeping",
            "technical_rna_normalize": True,
        }
    ]
    assert list(out.columns) == ["Ensembl_Gene_ID", "Symbol", "expression"]
    assert out["expression"].tolist() == [42.0]


def test_cancer_enriched_genes_preserves_legacy_columns(monkeypatch):
    """The trufflepig surface keeps the historical ``fold_over_others``
    column instead of exposing pirlygenes' newer ``fold_change`` schema."""
    import pandas as pd

    def fake_pan_cancer_expression(**kwargs):
        assert kwargs == {
            "normalize": "housekeeping",
            "technical_rna_normalize": True,
        }
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG_A", "ENSG_B", "ENSG_C"],
                "Symbol": ["A", "B", "C"],
                "PRAD_TPM": [10.0, 1.0, 6.0],
                "BRCA_TPM": [1.0, 10.0, 2.0],
                "LUAD_TPM": [3.0, 8.0, 2.0],
            }
        )

    monkeypatch.setattr(gsc, "pan_cancer_expression", fake_pan_cancer_expression)

    out = gsc.cancer_enriched_genes("PRAD", min_fold=2.0, min_expression=0.0)

    assert list(out["Symbol"]) == ["A", "C"]
    assert "fold_over_others" in out.columns
    assert "fold_change" not in out.columns
    assert out["fold_over_others"].tolist() == pytest.approx([5.0, 3.0])
