"""Trufflepig-surface contracts for reference accessors.

Pirlygenes owns the ID-keyed HPA/pan-cancer matrix and normalization
primitives. Trufflepig owns the deconvolved tumor-only artifacts
generated by its decomposition code. The tests below pin that boundary:

- ``trufflepig.reference.pan_cancer_expression()`` flips
  ``renormalize_to_million`` to True by default (pirlygenes' own
  default is False, so the user RNA-seq path here lands on a true
  TPM-1e6 footing without each caller having to opt in).
- ``tcga_<CODE>`` symbol-joined deconvolution columns are not part of
  the default pan-cancer frame.
- Deconvolved tumor-only references are loaded through explicit
  trufflepig accessors.
"""

import numpy as np
import pytest

import trufflepig.reference as gsc


def _reject_legacy_full_summary_load(monkeypatch, oncoref_expression, reject):
    """Guard the legacy multi-GB union loader when that dependency version has it.

    Newer oncoref releases read bounded per-source shards and no longer expose
    ``_reference_summary_frame``.  In that case there is no full-frame helper
    to guard, and the public result assertions below remain the compatibility
    contract.
    """
    if hasattr(oncoref_expression, "_reference_summary_frame"):
        monkeypatch.setattr(
            oncoref_expression,
            "_reference_summary_frame",
            reject,
        )


def test_pan_cancer_expression_renormalizes_to_million_by_default():
    """Trufflepig default: every value column should sum to ~1e6 so the
    analysis pipeline can compare user-sample TPM to cohort columns on
    a shared per-million footing."""
    df = gsc.pan_cancer_expression()
    value_cols = [c for c in df.columns if c.endswith(("_TPM", "_nTPM"))]
    assert value_cols, "expected per-tissue / per-cohort value columns"
    for sample_col in (
        next(c for c in value_cols if c.endswith("_TPM")),
        next(c for c in value_cols if c.endswith("_nTPM")),
    ):
        col_sum = float(df[sample_col].astype(float).sum(skipna=True))
        assert col_sum == pytest.approx(1e6, rel=1e-3), (sample_col, col_sum)
    assert any(c.endswith("_TPM_raw") for c in df.columns)
    assert any(c.endswith("_TPM_clean") for c in df.columns)
    assert not any(
        c.startswith(("FPKM_", "TPM_", "nTPM_", "TPM_clean_", "nTPM_clean_"))
        or c.endswith("_FPKM")
        for c in df.columns
    )
    assert not any(c.startswith("tcga_") for c in df.columns)


def test_pan_cancer_clean_values_are_default_and_raw_qc_signal_is_explicit():
    from pirlygenes.gene_sets_cancer import mitochondrial_gene_names

    mt_genes = set(mitochondrial_gene_names())
    df = gsc.pan_cancer_expression()

    mt_rows = df["Symbol"].isin(mt_genes)
    mt_raw = float(df.loc[mt_rows, "COAD_TPM_raw"].sum())
    mt_clean = float(df.loc[mt_rows, "COAD_TPM_clean"].sum())
    mt_alias = float(df.loc[mt_rows, "COAD_TPM"].sum())
    assert mt_raw > 0
    # New clean-TPM definition PINS the technical compartment to a fixed fraction
    # (not zeroed) — mt is present in clean below its raw level, and the clean alias
    # tracks the clean column. (trufflepig defers the fraction to pirlygenes.)
    assert 0.0 < mt_clean < mt_raw
    assert mt_alias == pytest.approx(mt_clean)
    clean_alias = df["COAD_TPM"]
    clean = df["COAD_TPM_clean"]
    assert ((clean_alias == clean) | (clean_alias.isna() & clean.isna())).all()


def test_pan_cancer_wrapper_overrides_pirlygenes_default_to_tpm(monkeypatch):
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()
    calls = []

    def fake_pan_cancer_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [1_000_000.0],
                "PRAD_TPM_clean": [1_000_000.0],
            }
        )

    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    try:
        gsc.pan_cancer_expression(genes=["KLK3"])
        gsc.pan_cancer_expression(genes=["KLK3"], technical_rna_normalize=True)

        assert calls == [
            {"genes": ("KLK3",), "normalize": ["tpm", "tpm_clean"]},
            {"genes": ("KLK3",), "normalize": ["tpm", "tpm_clean"]},
        ]
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_dependency_owned_reference_mirrors_are_not_local_csv_sources(monkeypatch):
    """Pan-cancer/HPA/ESTIMATE are dependency-owned mirrors.

    Trufflepig may transform their public pirlygenes frames into a stable local
    schema, but it must not read stale local CSV snapshots for these references.
    HPA still passes through the same normalize/assert-clean path used for
    sample-comparable expression.
    """
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()
    gsc._hpa_cell_type_expression_cached.cache_clear()
    hpa_source = pd.DataFrame(
        {
            "Ensembl_Gene_ID": ["ENSG000001"],
            "Symbol": ["GENE1"],
            "Cell type A": [5.0],
        }
    )
    estimate_source = pd.DataFrame({"gene": ["GENE1"], "signature": ["immune"]})
    calls = []
    real_read_csv = gsc.pd.read_csv
    forbidden_mirrors = {
        str(gsc.TRUFFLEPIG_DATA_DIR / "pan-cancer-expression.csv"),
        str(gsc.TRUFFLEPIG_DATA_DIR / "hpa-cell-type-expression.csv"),
        str(gsc.TRUFFLEPIG_DATA_DIR / "estimate-signatures.csv"),
    }

    def forbid_local_mirror_csv(path, *args, **kwargs):
        if str(path) in forbidden_mirrors:
            raise AssertionError(f"unexpected local mirror CSV read: {path!r}")
        return real_read_csv(path, *args, **kwargs)

    def fake_pan_cancer_expression(**kwargs):
        calls.append(("pan", kwargs))
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG000001"],
                "Symbol": ["GENE1"],
                "COAD_TPM_raw": [100.0],
                "COAD_TPM_clean": [75.0],
            }
        )

    def fake_hpa_cell_type_expression():
        calls.append(("hpa", {}))
        return hpa_source.copy()

    def fake_estimate_signatures():
        calls.append(("estimate", {}))
        return estimate_source.copy()

    def fake_normalize_expression(df, *, label_col, id_col, value_cols, **kwargs):
        calls.append(
            (
                "normalize",
                {
                    "label_col": label_col,
                    "id_col": id_col,
                    "value_cols": tuple(value_cols),
                },
            )
        )
        return df.copy(), {"method": "fake"}

    def fake_assert_clean_tpm(df, *, value_cols, context, **kwargs):
        calls.append(
            (
                "assert_clean",
                {
                    "context": context,
                    "value_cols": tuple(value_cols),
                },
            )
        )

    monkeypatch.setattr(gsc.pd, "read_csv", forbid_local_mirror_csv)
    monkeypatch.setattr(gsc._pirlygenes, "pan_cancer_expression", fake_pan_cancer_expression)
    monkeypatch.setattr(
        gsc._pirlygenes,
        "hpa_cell_type_expression",
        fake_hpa_cell_type_expression,
    )
    monkeypatch.setattr(gsc._pirlygenes, "estimate_signatures", fake_estimate_signatures)
    monkeypatch.setattr(gsc._pirlygenes, "normalize_expression", fake_normalize_expression)
    monkeypatch.setattr(gsc, "assert_clean_tpm", fake_assert_clean_tpm)
    try:
        pan = gsc.pan_cancer_expression()
        hpa = gsc.hpa_cell_type_expression()
        estimate = gsc.estimate_signatures()
    finally:
        gsc._PAN_CANCER_CACHE.clear()
        gsc._hpa_cell_type_expression_cached.cache_clear()

    assert pan.loc[0, "COAD_TPM"] == 75.0
    assert hpa.loc[0, "Cell type A"] == 5.0
    assert estimate.equals(estimate_source)
    assert ("pan", {"genes": None, "normalize": ["tpm", "tpm_clean"]}) in calls
    assert ("hpa", {}) in calls
    assert ("estimate", {}) in calls
    assert (
        "normalize",
        {
            "label_col": "Symbol",
            "id_col": "Ensembl_Gene_ID",
            "value_cols": ("Cell type A",),
        },
    ) in calls
    assert (
        "assert_clean",
        {
            "context": "hpa_cell_type_expression",
            "value_cols": ("Cell type A",),
        },
    ) in calls


def test_pan_cancer_expression_rejects_legacy_unit_prefix_columns():
    import pandas as pd

    with pytest.raises(ValueError, match="legacy unit-prefix"):
        gsc._standardize_pan_cancer_columns(
            pd.DataFrame(
                {
                    "Ensembl_Gene_ID": ["ENSG00000142515"],
                    "Symbol": ["KLK3"],
                    "TPM_clean_PRAD": [1.0],
                }
            )
        )


def test_pan_cancer_expression_rejects_native_scale_opt_out():
    # The native-scale opt-out (``renormalize_to_million=False``) was removed
    # in the cancer-type-evidence consolidation pass — callers can no longer
    # request native-scale data from any trufflepig reference accessor.
    with pytest.raises(TypeError):
        gsc.pan_cancer_expression(renormalize_to_million=False)


def test_pan_cancer_expression_excludes_symbol_joined_deconvolved_columns():
    df = gsc.pan_cancer_expression(genes=["KLK3"])
    tcga_cols = [c for c in df.columns if c.startswith("tcga_")]
    assert tcga_cols == []


def test_pan_cancer_expression_gene_filter_preserves_reference_scale(monkeypatch):
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()

    def fake_pan_cancer_expression(**kwargs):
        assert kwargs["genes"] == ("KLK3",)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [12_345.0],
                "PRAD_TPM_clean": [23_456.0],
            }
        )

    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    try:
        df = gsc.pan_cancer_expression(genes=["KLK3"])
        assert df.loc[0, "PRAD_TPM_raw"] == pytest.approx(12_345.0)
        assert df.loc[0, "PRAD_TPM_clean"] == pytest.approx(23_456.0)
        assert df.loc[0, "PRAD_TPM"] == pytest.approx(23_456.0)
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_pan_cancer_expression_percentile_validates_clean_tpm_only(monkeypatch):
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()

    def fake_pan_cancer_expression(**kwargs):
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515", "ENSG00000211459"],
                "Symbol": ["KLK3", "MT-RNR1"],
                "PRAD_TPM": [100.0, 0.0],
                "PRAD_TPM_clean": [100.0, 0.0],
            }
        )

    def fake_percentile_rank_expression(df, *, value_cols):
        out = df.copy()
        for col in value_cols:
            out[col] = [1.0, 0.5]
        return out, {"method": "fake"}

    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    monkeypatch.setattr(
        gsc._pirlygenes,
        "percentile_rank_expression",
        fake_percentile_rank_expression,
    )
    try:
        df = gsc.pan_cancer_expression(normalize="percentile")
        assert df.loc[df["Symbol"].eq("MT-RNR1"), "PRAD_TPM"].iloc[0] == 0.5
        assert df.loc[df["Symbol"].eq("MT-RNR1"), "PRAD_TPM_clean"].iloc[0] == 0.0
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_tcga_deconvolved_expression_is_explicit_trufflepig_reference():
    df = gsc.tcga_deconvolved_expression()
    assert {"symbol", "cancer_code", "tumor_tpm_median"}.issubset(df.columns)
    assert "Ensembl_Gene_ID" in df.columns
    assert "PRAD" in set(df["cancer_code"].astype(str))
    mapped = df["Ensembl_Gene_ID"].notna().mean()
    assert mapped > 0.99


def test_tcga_deconvolved_expression_renormalizes_per_group_by_default():
    df = gsc.tcga_deconvolved_expression()
    grp = df.groupby("cancer_code", dropna=False)["tumor_tpm_median"].sum()
    nonzero = grp[grp > 0]
    assert len(nonzero) > 0
    median_sum = float(nonzero.median())
    assert median_sum == pytest.approx(1e6, rel=1e-3), median_sum


def test_deconvolved_renormalization_preserves_quantile_order(monkeypatch):
    import pandas as pd

    fake = pd.DataFrame(
        {
            "Ensembl_Gene_ID": ["ENSG00000142515", "ENSG00000121410"],
            "symbol": ["KLK3", "A1BG"],
            "cancer_code": ["PRAD", "PRAD"],
            "tumor_tpm_q1": [9.0, 1.0],
            "tumor_tpm_median": [10.0, 30.0],
            "tumor_tpm_q3": [11.0, 31.0],
            "n_samples": [2, 2],
        }
    )

    monkeypatch.setattr(
        gsc,
        "_tcga_deconvolved_expression_cached",
        lambda: fake,
    )

    out = gsc.tcga_deconvolved_expression()
    row = out[out["symbol"] == "KLK3"].iloc[0]
    assert row["tumor_tpm_q1"] <= row["tumor_tpm_median"] <= row["tumor_tpm_q3"]
    assert out.groupby("cancer_code")["tumor_tpm_median"].sum().iloc[0] == pytest.approx(
        1_000_000.0
    )


def test_tcga_deconvolved_expression_rejects_native_scale_opt_out():
    with pytest.raises(TypeError):
        gsc.tcga_deconvolved_expression(renormalize_to_million=False)


def test_matched_normal_marker_panels_are_explicit_trufflepig_references():
    solid = gsc.tumor_up_vs_matched_normal("BRCA")
    heme = gsc.heme_tumor_up_vs_matched_normal("DLBC")

    assert set(solid["cancer_code"]) == {"BRCA"}
    assert {"symbol", "ensembl_gene_id", "tumor_tpm"}.issubset(solid.columns)
    assert set(heme["cancer_code"]) == {"DLBC"}
    assert {"symbol", "ensembl_gene_id", "tumor_tpm"}.issubset(heme.columns)


def test_pan_cancer_expression_cache_returns_defensive_copies(monkeypatch):
    """The trufflepig shim caches transformed frames but callers still
    receive copies they can mutate safely."""
    import pandas as pd

    gsc._PAN_CANCER_CACHE.clear()
    calls = []

    def fake_pan_cancer_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [1_000_000.0],
                "PRAD_TPM_clean": [1_000_000.0],
            }
        )

    monkeypatch.setattr(
        gsc._pirlygenes,
        "pan_cancer_expression",
        fake_pan_cancer_expression,
    )
    try:
        first = gsc.pan_cancer_expression(genes=["klk3"])
        first.loc[0, "PRAD_TPM"] = 99.0
        second = gsc.pan_cancer_expression(genes=["KLK3"])

        assert len(calls) == 1
        assert second.loc[0, "PRAD_TPM"] == 1_000_000.0
    finally:
        gsc._PAN_CANCER_CACHE.clear()


def test_subtype_deconvolved_expression_renormalizes_per_group_by_default():
    """Trufflepig default: each (cancer_code, subtype) group's
    tumor_tpm_median should sum to ~1e6 so cross-subtype comparisons are
    on a per-million footing."""
    df = gsc.subtype_deconvolved_expression()
    # Pick a well-populated cohort to avoid sparse-subtype edge cases.
    grp = df.groupby(["cancer_code", "subtype"], dropna=False)["tumor_tpm_median"].sum()
    nonzero = grp[grp > 0]
    assert len(nonzero) > 0
    median_sum = float(nonzero.median())
    assert median_sum == pytest.approx(1e6, rel=1e-3), median_sum


def test_subtype_deconvolved_expression_rejects_native_scale_opt_out():
    with pytest.raises(TypeError):
        gsc.subtype_deconvolved_expression(renormalize_to_million=False)


def test_cancer_reference_manifest_uses_loader_identity_and_metadata_counts(
    monkeypatch,
):
    """Loader provenance wins while compact build counts remain available."""
    import oncoref
    import oncoref.expression as oncoref_expression
    import pandas as pd
    from pirlygenes.expression import accessors

    from trufflepig import cancer_ontology

    metadata = pd.DataFrame(
        {
            "cancer_code": ["NEC_MERKEL"],
            "source_cohort": ["STALE_METADATA_ALIAS"],
            "n_cohort_samples": [91],
            "processing_pipeline": ["fixture"],
        }
    )
    metadata_calls = []
    availability_calls = []

    def compact_metadata(**kwargs):
        metadata_calls.append(kwargs)
        return metadata.copy()

    def compact_availability(**kwargs):
        availability_calls.append(kwargs)
        return pd.DataFrame(
            {
                "cancer_code": ["NEC_MERKEL"],
                "source_cohort": ["GSE235092_MERKEL_2024"],
                "available": [True],
                "n_reference_samples": [92],
            }
        )

    def reject_heavy_path(*args, **kwargs):
        raise AssertionError("summary expression frame was loaded")

    empty_registry = pd.DataFrame(
        columns=[
            "code",
            "source_cohort",
            "expression_source",
            "reference_source",
            "classification_reference_code",
        ]
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        compact_metadata,
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        compact_availability,
    )
    _reject_legacy_full_summary_load(
        monkeypatch,
        oncoref_expression,
        reject_heavy_path,
    )
    monkeypatch.setattr(accessors, "_full_canonical_views", reject_heavy_path)
    monkeypatch.setattr(
        gsc._pirlygenes,
        "available_cancer_expression_references",
        reject_heavy_path,
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: empty_registry,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert metadata_calls == [{"auto_fetch": False, "on_missing": "empty"}]
    assert availability_calls == [
        {
            "normalize": "tpm_clean",
            "reference_source": "artifact",
            "sample_qc": "artifact",
        }
    ]
    assert result[["cancer_code", "source_cohort"]].to_dict("records") == [
        {
            "cancer_code": "NEC_MERKEL",
            "source_cohort": "GSE235092_MERKEL_2024",
        }
    ]
    assert result.loc[0, "n_samples"] == 91
    assert result.loc[0, "processing_pipeline"] == "fixture"


def test_cancer_reference_manifest_reads_availability_before_optional_metadata(
    monkeypatch,
):
    """Cold discovery must not cache the pre-bundle compatibility fallback."""
    import oncoref
    import pandas as pd

    from trufflepig import cancer_ontology

    bundle_ready = False

    def build_metadata(**kwargs):
        assert bundle_ready, "metadata was read before the shard bundle was present"
        assert kwargs == {"auto_fetch": False, "on_missing": "empty"}
        return pd.DataFrame(
            {
                "cancer_code": ["NBL", "MTC", "SARC_MYXLPS"],
                "source_cohort": ["STALE_NBL", "STALE_MTC", "STALE_MYXLPS"],
                "n_cohort_samples": [155, 49, 28],
            }
        )

    def artifact_availability(**kwargs):
        nonlocal bundle_ready
        bundle_ready = True
        assert kwargs == {
            "normalize": "tpm_clean",
            "reference_source": "artifact",
            "sample_qc": "artifact",
        }
        return pd.DataFrame(
            {
                "cancer_code": ["NBL", "MTC", "SARC_MYXLPS"],
                "source_cohort": [
                    "TARGET_NBL_2018",
                    "GSE32662_PRINGLE_2012",
                    "GSE30929_SINGER_2007_LPS",
                ],
                "available": [True, True, True],
            }
        )

    empty_registry = pd.DataFrame(
        columns=[
            "code",
            "source_cohort",
            "expression_source",
            "reference_source",
            "classification_reference_code",
        ]
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        build_metadata,
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        artifact_availability,
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: empty_registry,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert result[["cancer_code", "source_cohort"]].to_dict("records") == [
        {"cancer_code": "NBL", "source_cohort": "TARGET_NBL_2018"},
        {"cancer_code": "MTC", "source_cohort": "GSE32662_PRINGLE_2012"},
        {
            "cancer_code": "SARC_MYXLPS",
            "source_cohort": "GSE30929_SINGER_2007_LPS",
        },
    ]


def test_cancer_reference_manifest_requires_a_matching_artifact_shard(monkeypatch):
    """Stale build metadata must not advertise an artifact that is absent."""
    import oncoref
    import pandas as pd

    from trufflepig import cancer_ontology

    metadata = pd.DataFrame(
        {
            "cancer_code": ["NEC_MERKEL", "STALE_FIXTURE"],
            "source_cohort": ["GSE235092_MERKEL_2024", "GSE_STALE"],
            "n_cohort_samples": [91, 12],
        }
    )
    empty_registry = pd.DataFrame(
        columns=[
            "code",
            "source_cohort",
            "expression_source",
            "reference_source",
            "classification_reference_code",
        ]
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        lambda **kwargs: metadata.copy(),
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        lambda **kwargs: pd.DataFrame(
            {
                "cancer_code": ["NEC_MERKEL"],
                "source_cohort": ["GSE235092_MERKEL_2024"],
                "available": [True],
            }
        ),
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: empty_registry,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert result["cancer_code"].tolist() == ["NEC_MERKEL"]


def test_cancer_reference_manifest_falls_back_to_artifact_availability(
    monkeypatch,
):
    """Older bundles without build metadata use only compact shard availability."""
    import oncoref
    import pandas as pd

    from trufflepig import cancer_ontology

    empty_metadata = pd.DataFrame(columns=["cancer_code", "source_cohort"])
    artifact_calls = []

    def artifact_availability(**kwargs):
        artifact_calls.append(kwargs)
        return pd.DataFrame(
            {
                "cancer_code": ["SARC_ESS_HG", "NEC_MERKEL"],
                "source_cohort": [
                    "GSE85383_YOSHIDA_2017_ESS",
                    "GSE235092_MERKEL_2024",
                ],
                "available": [True, True],
                "n_reference_samples": [4, 91],
            }
        )

    empty_registry = pd.DataFrame(
        columns=[
            "code",
            "source_cohort",
            "expression_source",
            "reference_source",
            "classification_reference_code",
        ]
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        lambda **kwargs: empty_metadata.copy(),
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        artifact_availability,
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: empty_registry,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert artifact_calls == [
        {
            "normalize": "tpm_clean",
            "reference_source": "artifact",
            "sample_qc": "artifact",
        }
    ]
    assert set(result["cancer_code"]) == {"SARC_ESS_HG", "NEC_MERKEL"}


def test_cancer_reference_manifest_preserves_verified_loader_identity(
    monkeypatch,
):
    """A registry provenance alias cannot rename an artifact-backed identity."""
    import oncoref
    import pandas as pd

    from trufflepig import cancer_ontology

    metadata = pd.DataFrame(
        {
            "cancer_code": ["SARC_WDLPS"],
            "source_cohort": ["METADATA_ALIAS"],
            "n_cohort_samples": [8],
        }
    )
    registry = pd.DataFrame(
        {
            "code": ["SARC_WDLPS"],
            "source_cohort": ["REGISTRY_ALIAS"],
            "expression_source": ["Treehouse"],
            "reference_source": ["own_cohort"],
            "classification_reference_code": ["SARC_WDLPS"],
        }
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        lambda **kwargs: metadata.copy(),
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        lambda **kwargs: pd.DataFrame(
            {
                "cancer_code": ["SARC_WDLPS"],
                "source_cohort": ["VERIFIED_LOADER_IDENTITY"],
                "available": [True],
            }
        ),
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: registry,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert result[["cancer_code", "source_cohort"]].to_dict("records") == [
        {
            "cancer_code": "SARC_WDLPS",
            "source_cohort": "VERIFIED_LOADER_IDENTITY",
        }
    ]


def test_cancer_reference_manifest_excludes_unavailable_parent_routes(
    monkeypatch,
):
    """Registry provenance cannot create direct artifacts for parent-routed codes."""
    import oncoref
    import pandas as pd

    from trufflepig import cancer_ontology

    metadata = pd.DataFrame(
        {
            "cancer_code": ["NEC_MERKEL"],
            "source_cohort": ["GSE235092_MERKEL_2024"],
            "n_cohort_samples": [91],
        }
    )
    registry = pd.DataFrame(
        {
            "code": ["MBL_G3", "NEC_MERKEL"],
            "source_cohort": [
                "TREEHOUSE_POLYA_25_01_MBL_SUBGROUP_MARKERS",
                "GSE235092_MERKEL_2024",
            ],
            "expression_source": ["Treehouse", "GEO"],
            "reference_source": ["parent", "own_cohort"],
            "classification_reference_code": ["MBL", "NEC_MERKEL"],
        }
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        lambda **kwargs: metadata.copy(),
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        lambda **kwargs: pd.DataFrame(
            {
                "cancer_code": ["NEC_MERKEL"],
                "source_cohort": ["GSE235092_MERKEL_2024"],
                "available": [True],
            }
        ),
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: registry,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert result["cancer_code"].tolist() == ["NEC_MERKEL"]
    assert result["source_cohort"].tolist() == ["GSE235092_MERKEL_2024"]


def test_cancer_reference_manifest_failure_uses_registry_without_summary(
    monkeypatch,
):
    """Broken compact metadata degrades to registry rows without heavy discovery."""
    import oncoref
    import oncoref.expression as oncoref_expression
    import pandas as pd

    from trufflepig import cancer_ontology

    def fail_metadata(**kwargs):
        raise RuntimeError("corrupt artifact metadata")

    def reject_heavy_path(*args, **kwargs):
        raise AssertionError("summary expression frame was loaded")

    registry = pd.DataFrame(
        {
            "code": ["MPLPS_FIXTURE"],
            "source_cohort": ["GSE_FIXTURE_MPLPS"],
            "expression_source": ["GEO"],
            "reference_source": ["own_cohort"],
            "classification_reference_code": ["MPLPS_FIXTURE"],
        }
    )
    gsc._cancer_reference_manifest_cached.cache_clear()
    monkeypatch.setattr(
        oncoref,
        "expression_artifact_build_metadata",
        fail_metadata,
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        reject_heavy_path,
    )
    _reject_legacy_full_summary_load(
        monkeypatch,
        oncoref_expression,
        reject_heavy_path,
    )
    monkeypatch.setattr(
        cancer_ontology,
        "cancer_type_registry",
        lambda: registry.copy(),
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    assert result[["cancer_code", "source_cohort"]].to_dict("records") == [
        {
            "cancer_code": "MPLPS_FIXTURE",
            "source_cohort": "GSE_FIXTURE_MPLPS",
        }
    ]


def test_cancer_reference_expression_uses_artifact_view(monkeypatch):
    """Expression loading consumes the same lightweight view as the manifest."""
    import oncoref
    import pandas as pd

    calls = []

    def artifact_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(columns=gsc._CANCER_REFERENCE_EMPTY_COLUMNS)

    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression",
        artifact_expression,
    )
    monkeypatch.setattr(
        gsc._pirlygenes,
        "cancer_reference_expression",
        lambda **kwargs: (_ for _ in ()).throw(
            AssertionError("pirlygenes summary view was loaded")
        ),
    )

    result = gsc.cancer_reference_expression(
        cancer_types=["NEC_MERKEL"],
        genes=[" mki67 ", "B7-H3"],
    )

    assert result.empty
    assert calls == [
        {
            "cancer_types": ["NEC_MERKEL"],
            "genes": ["MKI67", "B7-H3", "CD276"],
            "normalize": "tpm_clean",
            "format": "long",
            "include_provenance": True,
            "on_missing": "empty",
            "auto_fetch": False,
            "sample_qc": "artifact",
            "reference_source": "artifact",
            "gene_id_style": "pirlygenes",
            "gene_universe": "pirlygenes",
        }
    ]


def test_cancer_reference_expression_reads_bounded_raw_qc_shards(
    monkeypatch,
    tmp_path,
):
    """Raw and raw-log QC use requested source shards once, never source matrices."""
    import oncoref
    import oncoref.expression as oncoref_expression
    import pandas as pd

    availability_calls = []

    def raw_availability(**kwargs):
        availability_calls.append(kwargs)
        assert kwargs == {
            "cancer_types": ["ACC", "MTC"],
            "normalize": "tpm_raw",
            "sample_qc": "all",
            "reference_source": "summary_rows_all",
            "all_sources": True,
        }
        return pd.DataFrame(
            {
                "cancer_code": ["ACC", "MTC"],
                "source_cohort": ["SHARED_SOURCE", "SHARED_SOURCE"],
                "available": [True, True],
                "n_reference_genes": [1, 1],
                "n_reference_samples": [10, 20],
            }
        )

    pd.DataFrame(
        {
            "Ensembl_Gene_ID": ["ENSG00000148773", "ENSG00000148773"],
            "Symbol": ["MKI67", "MKI67"],
            "cancer_code": ["ACC", "MTC"],
            "source_cohort": ["SHARED_SOURCE", "SHARED_SOURCE"],
            "TPM_median": [3.0, 7.0],
            "TPM_q1": [1.0, 2.0],
            "TPM_q3": [5.0, 9.0],
            "n_samples": [10, 20],
            "n_detected": [10, 20],
        }
    ).to_csv(tmp_path / "SHARED_SOURCE.csv.gz", index=False)

    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression_availability",
        raw_availability,
    )
    monkeypatch.setattr(
        oncoref_expression,
        "_bundle_subdir",
        lambda *args, **kwargs: tmp_path,
    )
    monkeypatch.setattr(
        oncoref,
        "cancer_reference_expression",
        lambda **kwargs: (_ for _ in ()).throw(
            AssertionError("raw QC tried to use the artifact/source-matrix accessor")
        ),
    )

    result = gsc.cancer_reference_expression(
        cancer_types=["ACC", "MTC"],
        genes=[" mki67 "],
        normalize=["tpm", "tpm_log1p"],
    )

    assert len(availability_calls) == 1
    assert result.attrs["reference_backend"] == "oncoref_bounded_summary_shards"
    assert result.attrs["sample_qc"] == "all"
    assert set(result["normalization"]) == {"TPM", "TPM_log1p"}
    assert {"Proteoform_ID", "Member_Ensembl_Gene_IDs"}.issubset(result.columns)
    assert result[["Proteoform_ID", "Member_Ensembl_Gene_IDs"]].notna().all().all()
    for code in ("ACC", "MTC"):
        rows = result[result["cancer_code"].eq(code)].set_index("normalization")
        assert rows.loc["TPM_log1p", "expression"] == pytest.approx(
            np.log1p(rows.loc["TPM", "expression"])
        )


def test_real_cancer_reference_expression_exposes_raw_and_clean_modes(monkeypatch):
    """Raw QC and downstream clean views coexist without loading source-union rows."""
    import oncoref.expression as oncoref_expression

    def reject_summary(*args, **kwargs):
        raise AssertionError("summary expression frame was loaded")

    _reject_legacy_full_summary_load(
        monkeypatch,
        oncoref_expression,
        reject_summary,
    )
    # Exercise the compatibility aliases as well as every distinct value space.
    modes = [
        "raw_tpm",
        "log1p_raw_tpm",
        "clean_tpm",
        "log1p_clean_tpm",
        "biological_clean_tpm",
    ]

    result = gsc.cancer_reference_expression(
        cancer_types=["MTC"],
        genes=[" mki67 "],
        normalize=modes,
    )

    assert set(result["normalization"]) == {
        "TPM",
        "TPM_log1p",
        "TPM_clean",
        "TPM_clean_log1p",
        "TPM_clean_biological",
    }
    assert result[["Proteoform_ID", "Member_Ensembl_Gene_IDs"]].notna().all().all()
    values = result.set_index("normalization")
    sources = values["source_cohort"]
    assert sources.loc["TPM"] == sources.loc["TPM_log1p"]
    assert sources.loc["TPM_clean"] == sources.loc["TPM_clean_log1p"]
    assert sources.loc["TPM_clean"] == sources.loc["TPM_clean_biological"]
    from trufflepig.analyze import effective_expression_reference

    reference = effective_expression_reference("MTC")
    assert reference is not None
    assert sources.loc["TPM_clean"] == reference.source
    for column in ("expression", "q1", "q3"):
        assert values.loc["TPM_log1p", column] == pytest.approx(
            np.log1p(values.loc["TPM", column])
        )
        assert values.loc["TPM_clean_log1p", column] == pytest.approx(
            np.log1p(values.loc["TPM_clean", column]),
            rel=1e-3,
        )
    assert values.loc["TPM", "expression"] != pytest.approx(
        values.loc["TPM_clean", "expression"]
    )


def test_real_cancer_reference_expression_mixed_modes_wide():
    """Wide output preserves one explicit column for every requested scale."""
    result = gsc.cancer_reference_expression(
        cancer_types=["MTC"],
        genes=["MKI67"],
        normalize=["tpm", "log1p_tpm", "tpm_clean", "tpm_clean_log1p"],
        format="wide",
    )

    assert result.columns.tolist() == [
        "Ensembl_Gene_ID",
        "Symbol",
        "MTC_TPM",
        "MTC_TPM_log1p",
        "MTC_TPM_clean",
        "MTC_TPM_clean_log1p",
    ]
    row = result.iloc[0]
    assert row["MTC_TPM_log1p"] == pytest.approx(np.log1p(row["MTC_TPM"]))
    assert row["MTC_TPM_clean_log1p"] == pytest.approx(
        np.log1p(row["MTC_TPM_clean"]),
        rel=1e-3,
    )


def test_real_mixed_wide_preserves_requested_columns_for_empty_gene_filter():
    """Availability defines the public schema even when no gene rows match."""
    result = gsc.cancer_reference_expression(
        cancer_types=["MTC"],
        genes=["NOT_A_REAL_GENE"],
        normalize=["tpm", "tpm_clean"],
        format="wide",
    )

    assert result.empty
    assert result.columns.tolist() == [
        "Ensembl_Gene_ID",
        "Symbol",
        "MTC_TPM",
        "MTC_TPM_clean",
    ]


def test_real_mixed_mode_provenance_is_order_independent():
    """Mixed raw/clean metadata describes each mode instead of the first one."""
    forward = gsc.cancer_reference_expression(
        cancer_types=["MTC"],
        genes=["MKI67"],
        normalize=["tpm", "tpm_clean"],
        format="wide",
    )
    reverse = gsc.cancer_reference_expression(
        cancer_types=["MTC"],
        genes=["MKI67"],
        normalize=["tpm_clean", "tpm"],
        format="wide",
    )

    assert forward.attrs["normalization_provenance"] == reverse.attrs[
        "normalization_provenance"
    ]
    provenance = forward.attrs["normalization_provenance"]
    assert provenance["TPM"] == {
        "reference_backend": "oncoref_bounded_summary_shards",
        "reference_source": "summary_rows_all",
        "sample_qc": "all",
    }
    assert provenance["TPM_clean"]["reference_backend"] == "oncoref_artifact"
    assert provenance["TPM_clean"]["reference_source"] == "artifact"
    assert provenance["TPM_clean"]["sample_qc"] == "artifact"
    for attr_name in ("reference_backend", "reference_source", "sample_qc"):
        assert attr_name not in forward.attrs
        assert attr_name not in reverse.attrs
    assert [row["normalization"] for row in forward.attrs["availability"]] == [
        row["normalization"] for row in reverse.attrs["availability"]
    ]


def test_real_raw_qc_preserves_source_cohorts_and_wide_selects_richest(monkeypatch):
    """Long QC stays source-specific; source-less wide output is deterministic."""
    import oncoref.expression as oncoref_expression

    _reject_legacy_full_summary_load(
        monkeypatch,
        oncoref_expression,
        lambda *args, **kwargs: (_ for _ in ()).throw(
            AssertionError("summary expression frame was loaded")
        ),
    )
    long = gsc.cancer_reference_expression(
        cancer_types=["SARC_DDLPS"],
        genes=["MDM2"],
        normalize="tpm",
    )
    assert set(long["source_cohort"]) == {
        "TREEHOUSE_POLYA_25_01_TCGA_SARC_HISTOLOGY",
        "GSE75885_DELESPAUL_2017",
        "GSE30929_SINGER_2007_LPS",
    }
    assert long.attrs["sample_qc"] == "all"

    wide = gsc.cancer_reference_expression(
        cancer_types=["SARC_DDLPS"],
        genes=["MDM2"],
        normalize="tpm",
        format="wide",
    )
    richest = long.loc[
        long["source_cohort"].eq("TREEHOUSE_POLYA_25_01_TCGA_SARC_HISTOLOGY"),
        "expression",
    ].iloc[0]
    assert wide.columns.tolist() == [
        "Ensembl_Gene_ID",
        "Symbol",
        "SARC_DDLPS_TPM",
    ]
    assert wide.loc[0, "SARC_DDLPS_TPM"] == pytest.approx(richest)


def test_real_cancer_reference_manifest_matches_loader_availability(monkeypatch):
    """The manifest publishes the compact artifact loader's exact identities."""
    import oncoref
    import oncoref.expression as oncoref_expression

    def reject_summary(*args, **kwargs):
        raise AssertionError("summary expression frame was loaded")

    availability = oncoref.cancer_reference_expression_availability(
        normalize="tpm_clean",
        reference_source="artifact",
        sample_qc="artifact",
    )
    available = availability["available"].fillna(False).astype(bool)
    expected = set(
        zip(
            availability.loc[available, "cancer_code"].astype(str),
            availability.loc[available, "source_cohort"].astype(str),
        )
    )

    gsc._cancer_reference_manifest_cached.cache_clear()
    _reject_legacy_full_summary_load(
        monkeypatch,
        oncoref_expression,
        reject_summary,
    )
    try:
        result = gsc.cancer_reference_manifest()
    finally:
        gsc._cancer_reference_manifest_cached.cache_clear()

    actual = set(
        zip(
            result["cancer_code"].astype(str),
            result["source_cohort"].astype(str),
        )
    )
    assert actual == expected
    assert len(result) == len(expected)


@pytest.mark.parametrize("code", ["LUAD", "MTC", "SARC_WDLPS", "SARC_ESS_HG"])
def test_manifest_source_identity_matches_loaded_artifact(code):
    """Every advertised source identity must be returned by its expression shard."""
    manifest = gsc.cancer_reference_manifest()
    source = manifest.loc[
        manifest["cancer_code"].astype(str).eq(code), "source_cohort"
    ].item()

    expression = gsc.cancer_reference_expression(
        cancer_types=[code],
        genes=["MKI67"],
    )

    assert not expression.empty
    assert set(expression["source_cohort"].astype(str)) == {str(source)}
    assert set(expression["normalization"].astype(str)) == {"TPM_clean"}


def test_cancer_expression_uses_trufflepig_reference_surface(monkeypatch):
    """Legacy helper composes trufflepig's pan-cancer wrapper, not the
    upstream pirlygenes default surface."""
    import pandas as pd

    calls = []

    def fake_pan_cancer_expression(**kwargs):
        calls.append(kwargs)
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG00000142515"],
                "Symbol": ["KLK3"],
                "PRAD_TPM": [42.0],
            }
        )

    monkeypatch.setattr(gsc, "pan_cancer_expression", fake_pan_cancer_expression)

    out = gsc.cancer_expression("PRAD", genes=["KLK3"])

    assert calls == [
        {
            "genes": ["KLK3"],
            "normalize": "housekeeping",
            "technical_rna_normalize": True,
        }
    ]
    assert list(out.columns) == ["Ensembl_Gene_ID", "Symbol", "expression"]
    assert out["expression"].tolist() == [42.0]


def test_cancer_enriched_genes_preserves_legacy_columns(monkeypatch):
    """The trufflepig surface keeps the historical ``fold_over_others``
    column instead of exposing pirlygenes' newer ``fold_change`` schema."""
    import pandas as pd

    def fake_pan_cancer_expression(**kwargs):
        assert kwargs == {
            "normalize": "housekeeping",
            "technical_rna_normalize": True,
        }
        return pd.DataFrame(
            {
                "Ensembl_Gene_ID": ["ENSG_A", "ENSG_B", "ENSG_C"],
                "Symbol": ["A", "B", "C"],
                "PRAD_TPM": [10.0, 1.0, 6.0],
                "BRCA_TPM": [1.0, 10.0, 2.0],
                "LUAD_TPM": [3.0, 8.0, 2.0],
            }
        )

    monkeypatch.setattr(gsc, "pan_cancer_expression", fake_pan_cancer_expression)

    out = gsc.cancer_enriched_genes("PRAD", min_fold=2.0, min_expression=0.0)

    assert list(out["Symbol"]) == ["A", "C"]
    assert "fold_over_others" in out.columns
    assert "fold_change" not in out.columns
    assert out["fold_over_others"].tolist() == pytest.approx([5.0, 3.0])


@pytest.mark.parametrize(
    "public,cached",
    [
        ("tcga_deconvolved_expression", "_tcga_deconvolved_normalized"),
        ("subtype_deconvolved_expression", "_subtype_deconvolved_normalized"),
    ],
)
def test_deconvolved_normalization_is_memoized(public, cached):
    """The normalize -> renormalize -> assert pipeline over the ~640k/1.05M-row
    deconvolved artifacts is pure in (raw read, bool args) and was being re-run
    on every call. It must now be memoized: a second call is served from the
    ``lru_cache`` (a hit), returns equal data, and a *distinct* object so callers
    can mutate without corrupting the cache.
    """
    fn = getattr(gsc, public)
    cache = getattr(gsc, cached)
    cache.cache_clear()

    first = fn()
    hits_before = cache.cache_info().hits
    second = fn()
    hits_after = cache.cache_info().hits

    assert hits_after == hits_before + 1, "second call should hit the cache"
    assert first.equals(second), "memoized output must equal a fresh build"
    assert first is not second, "callers must get an independent copy"

    # Mutating a returned frame must not corrupt the cached frame.
    value_col = next(c for c in ("tumor_tpm_median",) if c in first.columns)
    first.iloc[0, first.columns.get_loc(value_col)] = -12345.0
    third = fn()
    assert third.iloc[0][value_col] != -12345.0
