"""Expression-backed reference data for the analysis engine.

Pirlygenes owns the ID-keyed pan-cancer/HPA reference matrix and the
normalization primitives. Trufflepig owns deconvolved tumor-only
artifacts generated by its decomposition code. The public trufflepig
surface exposes normalized ``<CODE>_TPM`` cohort columns by default and
keeps symbol-level deconvolved references behind explicit accessors.
"""

from __future__ import annotations

from functools import lru_cache

import numpy as np
import pandas as pd
import pirlygenes as _pirlygenes
from pirlygenes.expression.qc import TECHNICAL_FRACTION

from ._data import TRUFFLEPIG_DATA_DIR
from .clean_tpm import assert_clean_tpm

# pirlygenes clean TPM pins the censored (technical-RNA + ribosomal) compartment
# to this fraction of the 1e6 budget — split into separately-pinned ribosomal
# (~16%) and other-technical (~9%) sub-compartments — rather than zeroing it.
# Import the PUBLIC pirlygenes constant so the guard tracks the value pirlygenes
# actually applies (surviving any future change) instead of a hardcoded copy.
_CLEAN_TPM_V4_TECHNICAL_FRACTION = TECHNICAL_FRACTION

_PAN_CANCER_CACHE: dict[tuple, pd.DataFrame] = {}
_TCGA_DECONV_PATH = TRUFFLEPIG_DATA_DIR / "tcga-deconvolved-expression.csv.gz"
_SUBTYPE_DECONV_PATH = TRUFFLEPIG_DATA_DIR / "subtype-deconvolved-expression.csv.gz"
_TUMOR_UP_MATCHED_NORMAL_PATH = TRUFFLEPIG_DATA_DIR / "tumor-up-vs-matched-normal.csv"
_HEME_TUMOR_UP_MATCHED_NORMAL_PATH = (
    TRUFFLEPIG_DATA_DIR / "heme-tumor-up-vs-matched-normal.csv"
)
_DECONV_VALUE_COLS = ("tumor_tpm_median", "tumor_tpm_q1", "tumor_tpm_q3")
_SUBTYPE_GROUP_COLS = ("cancer_code", "subtype")
_CANCER_REFERENCE_EMPTY_COLUMNS = [
    "Ensembl_Gene_ID",
    "Symbol",
    "cancer_code",
    "source_cohort",
    "source_project",
    "source_version",
    "n_samples",
    "n_detected",
    "processing_pipeline",
    "notes",
    "normalization",
    "expression",
    "q1",
    "q3",
]


def _artifact_reference_manifest(oncoref) -> pd.DataFrame:
    """Return the compact manifest for the artifact-backed expression view.

    The summary-row availability API is gene-independent but not lightweight:
    oncoref 1.8.132 builds it by materializing the roughly five-million-row
    reference summary.  Artifact build metadata is a small CSV emitted beside
    the percentile shards and contains the exact source identity and sample
    count served by ``reference_source="artifact"``.

    Current bundles require one metadata row per percentile shard.  Older
    supported bundles that lack the sidecar fall back to artifact availability,
    whose implementation enumerates shard filenames and never touches the
    summary expression frame.
    """
    metadata_accessor = getattr(
        oncoref, "expression_artifact_build_metadata", None
    )
    shard_accessor = getattr(oncoref, "available_percentile_cohorts", None)
    if callable(metadata_accessor) and callable(shard_accessor):
        # Enumerating shards ensures the released bundle is present. Reading
        # optional metadata first on a cold install returns an empty frame;
        # caching the ensuing compatibility fallback then permanently omits
        # valid direct cohorts such as NBL, MTC, and SARC_MYXLPS in that process.
        available_codes = frozenset(str(code) for code in shard_accessor())
        metadata = metadata_accessor(auto_fetch=False, on_missing="empty")
        if {"cancer_code", "source_cohort"}.issubset(metadata.columns):
            manifest = metadata[
                metadata["cancer_code"].astype(str).isin(available_codes)
            ].copy()
            metadata_codes = frozenset(manifest["cancer_code"].astype(str))
            if metadata_codes == available_codes:
                if "n_cohort_samples" in manifest.columns:
                    manifest["n_samples"] = pd.to_numeric(
                        manifest["n_cohort_samples"], errors="coerce"
                    )
                manifest["available"] = True
                return manifest

    availability_accessor = getattr(
        oncoref, "cancer_reference_expression_availability", None
    )
    if not callable(availability_accessor):
        raise AttributeError("oncoref has no artifact manifest accessor")
    # ``sample_qc='artifact'`` is not accepted by the availability API in
    # oncoref 1.8.x.  Availability under ``pass`` still means the percentile
    # shard exists; trufflepig reads that shard under its recorded build policy.
    return availability_accessor(
        normalize="tpm_clean",
        reference_source="artifact",
        sample_qc="pass",
    )


def _parse_pan_value_column(col: str) -> tuple[str, int] | None:
    """Return ``(trufflepig_column, priority)`` for expression value columns.

    Trufflepig follows the pirlygenes 5.2 entity-first surface and keeps
    both raw and technical-RNA-clean views explicit:
    ``<tissue>_nTPM_raw`` / ``<cancer>_TPM_raw`` and
    ``<tissue>_nTPM_clean`` / ``<cancer>_TPM_clean``.
    """
    if col.startswith("tcga_"):
        return "", 0
    legacy_unit_prefixes = (
        "nTPM_clean_",
        "TPM_clean_",
        "nTPM_raw_",
        "TPM_raw_",
        "nTPM_",
        "TPM_",
        "FPKM_",
    )
    if col.startswith(legacy_unit_prefixes):
        raise ValueError(
            "pirlygenes returned a legacy unit-prefix expression column "
            f"{col!r}; trufflepig requires entity-first columns like "
            "'PRAD_TPM_clean'"
        )
    # Recognized normalized/provenance variants that should not leak through.
    drop_suffixes = (
        "_nTPM_hk",
        "_TPM_hk",
        "_nTPM_percentile",
        "_TPM_percentile",
        "_FPKM",
    )
    if col.endswith(drop_suffixes):
        return "", 0

    suffix_rules = (
        ("_nTPM_clean", "_nTPM_clean", 40),
        ("_TPM_clean", "_TPM_clean", 40),
        ("_nTPM_raw", "_nTPM_raw", 30),
        ("_TPM_raw", "_TPM_raw", 30),
        ("_nTPM", "_nTPM_raw", 20),
        ("_TPM", "_TPM_raw", 20),
    )
    for source_suffix, target_suffix, priority in suffix_rules:
        if col.endswith(source_suffix):
            return f"{col[: -len(source_suffix)]}{target_suffix}", priority
    return None


def _standardize_pan_cancer_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Convert pirlygenes' pan-cancer frame to trufflepig's stable schema."""
    selected: dict[str, tuple[int, str, int]] = {}
    non_value_cols: list[str] = []
    for position, col in enumerate(df.columns):
        parsed = _parse_pan_value_column(str(col))
        if parsed is None:
            non_value_cols.append(col)
            continue
        target, priority = parsed
        if not target:
            continue
        old = selected.get(target)
        if old is None or priority > old[0]:
            selected[target] = (priority, col, position)

    ordered_targets = sorted(selected, key=lambda target: selected[target][2])
    columns = {col: df[col] for col in non_value_cols}
    for target in ordered_targets:
        _priority, source, _position = selected[target]
        columns[target] = df[source]
    # Analysis-facing aliases (`*_TPM`, `*_nTPM`) intentionally shadow the
    # "raw" semantics they had under pirlygenes 5.1 — they now point at the
    # technical-RNA-clean columns so every analysis path sees the same
    # sanitized values. Callers that need raw must read `*_TPM_raw` /
    # `*_nTPM_raw` explicitly.
    for target in ordered_targets:
        if target.endswith("_TPM_clean"):
            alias = target.removesuffix("_clean")
        elif target.endswith("_nTPM_clean"):
            alias = target.removesuffix("_clean")
        else:
            continue
        columns.setdefault(alias, df[selected[target][1]])
    return pd.DataFrame(columns, index=df.index).copy()


def _canonicalize_cancer_code_column(df: pd.DataFrame) -> pd.DataFrame:
    """Resolve the ``cancer_code`` column through pirlygenes' alias resolver.

    The bundled deconvolved artifacts predate pirlygenes' Phase-C code renames
    (e.g. ``CHON``→``SARC_CHON``), so a sample looked up by its *new* registry
    code would silently miss its subtype reference and fall back to broad SARC.
    Canonicalizing on load — using the now-shipped ``CANCER_TYPE_ALIASES`` — keeps
    the artifact correct without a regeneration and auto-absorbs future rename
    waves. Codes with no alias (legacy cohort-name leakage like ``BEATAML`` /
    ``TARGET_*``, a separate data-gen issue) are left unchanged. See #53.
    """
    if "cancer_code" not in df.columns:
        return df
    from trufflepig.cancer_ontology import resolve_cancer_type

    def _resolve(code: str) -> str:
        try:
            return resolve_cancer_type(code)
        except Exception:
            return code

    uniques = df["cancer_code"].dropna().astype(str).unique()
    mapping = {code: _resolve(code) for code in uniques}
    df["cancer_code"] = df["cancer_code"].map(
        lambda c: mapping.get(str(c), c) if pd.notna(c) else c
    )
    return df


@lru_cache(maxsize=1)
def _tcga_deconvolved_expression_cached() -> pd.DataFrame:
    df = pd.read_csv(_TCGA_DECONV_PATH, low_memory=False)
    df = _canonicalize_cancer_code_column(df)
    # Relabel byte-identical-protein members to the proteoform id BEFORE the
    # normalize→renormalize-to-1e6 pipeline, so the per-cancer TPM-1e6 invariant
    # is preserved after the member rows are folded out (see
    # common.relabel_proteoform_symbols_long — medians are not summed, the
    # dominant-locus row is kept; true summation belongs to the upstream generator).
    from trufflepig.common import relabel_proteoform_symbols_long

    return relabel_proteoform_symbols_long(
        df,
        symbol_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        dedup_keys=("symbol", "cancer_code"),
        value_col="tumor_tpm_median",
    )


@lru_cache(maxsize=1)
def _subtype_deconvolved_expression_cached() -> pd.DataFrame:
    df = pd.read_csv(_SUBTYPE_DECONV_PATH, low_memory=False)
    df = _canonicalize_cancer_code_column(df)
    from trufflepig.common import relabel_proteoform_symbols_long

    return relabel_proteoform_symbols_long(
        df,
        symbol_col="symbol",
        dedup_keys=("symbol", "cancer_code", "subtype", "source_cohort"),
        value_col="tumor_tpm_median",
    )


@lru_cache(maxsize=1)
def _tumor_up_vs_matched_normal_cached() -> pd.DataFrame:
    return pd.read_csv(_TUMOR_UP_MATCHED_NORMAL_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _heme_tumor_up_vs_matched_normal_cached() -> pd.DataFrame:
    return pd.read_csv(_HEME_TUMOR_UP_MATCHED_NORMAL_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _hpa_cell_type_expression_cached() -> pd.DataFrame:
    df = _pirlygenes.hpa_cell_type_expression().copy()
    value_cols = [
        col
        for col in df.columns
        if col not in {"Ensembl_Gene_ID", "Symbol"}
        and pd.api.types.is_numeric_dtype(df[col])
    ]
    # Proteoform-collapse (SUM) the linear cell-type nTPM matrix before normalize.
    from trufflepig.common import collapse_proteoform_loci

    if value_cols:
        df = collapse_proteoform_loci(df, value_cols=value_cols)
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="Symbol",
        id_col="Ensembl_Gene_ID",
        value_cols=value_cols,
    )
    assert_clean_tpm(
        df,
        value_cols=value_cols,
        context="hpa_cell_type_expression",
    )
    return df


def _filter_cancer_code(df: pd.DataFrame, cancer_code: str | None) -> pd.DataFrame:
    if cancer_code is None:
        return df.reset_index(drop=True)
    code = str(cancer_code).upper()
    return df[df["cancer_code"].astype(str).str.upper() == code].reset_index(drop=True)


def _renormalize_long_groups_to_million(
    df: pd.DataFrame,
    *,
    value_cols: tuple[str, ...],
    group_cols: tuple[str, ...],
    reference_col: str | None = None,
) -> pd.DataFrame:
    out = df.copy()
    if not value_cols:
        return out
    reference_col = reference_col or value_cols[0]
    groupers = [out[col] for col in group_cols]
    reference_values = pd.to_numeric(out[reference_col], errors="coerce")
    totals = reference_values.groupby(groupers, dropna=False).transform("sum")
    mask = totals > 0
    scales = 1_000_000.0 / totals.where(mask)
    for col in value_cols:
        values = pd.to_numeric(out[col], errors="coerce")
        out[col] = values.where(~mask, values * scales)
    return out


def _analysis_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM", "_TPM"))
    ]


def _raw_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM_raw", "_TPM_raw"))
    ]


def _clean_companion_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM_clean", "_TPM_clean"))
    ]


def _all_wide_tpm_value_cols(df: pd.DataFrame) -> list[str]:
    return _raw_value_cols(df) + _clean_companion_value_cols(df) + _analysis_value_cols(df)


def _apply_trufflepig_pan_normalize(
    df: pd.DataFrame,
    normalize,
    log_transform: bool,
) -> pd.DataFrame:
    value_cols = _analysis_value_cols(df)
    if isinstance(normalize, (list, tuple, set)):
        modes = {str(mode).lower() for mode in normalize}
        if modes <= {"tpm", "tpm_clean"}:
            normalize = "tpm_clean"
        elif "housekeeping" in modes or "hk" in modes:
            normalize = "housekeeping"
        elif "percentile" in modes:
            normalize = "percentile"
    if normalize is None or normalize in {"tpm", "TPM", "tpm_clean"}:
        out = df
    elif normalize in {"housekeeping", "hk"}:
        out = _pirlygenes.normalize_to_housekeeping(df, value_cols=value_cols)
    elif normalize == "percentile":
        out, _ = _pirlygenes.percentile_rank_expression(df, value_cols=value_cols)
    else:
        raise ValueError(
            "normalize must be None, 'tpm', 'tpm_clean', 'housekeeping', "
            "'hk', or 'percentile'; "
            f"got {normalize!r}"
        )
    if log_transform:
        out = _pirlygenes.log2_transform(out, value_cols=value_cols)
    return out


def _load_pan_cancer_from_pirlygenes(
    *,
    genes_tuple,
    remove_noncoding: bool,
) -> pd.DataFrame:
    # Trufflepig pins pirlygenes>=5.2,<6 (see pyproject.toml), which provides
    # the entity-first ``normalize=["tpm", "tpm_clean"]`` preset and clean
    # TPM columns by default. Earlier pirlygenes APIs are not supported.
    if remove_noncoding:
        return _pirlygenes.pan_cancer_expression(
            genes=genes_tuple,
            normalize=["tpm", "tpm_clean"],
            technical_rna_normalize=True,
            remove_noncoding=True,
            renormalize_to_million=True,
        )
    return _pirlygenes.pan_cancer_expression(
        genes=genes_tuple,
        normalize=["tpm", "tpm_clean"],
    )


def _pan_cancer_cache_key(
    genes,
    normalize,
    log_transform,
    technical_rna_normalize,
    remove_noncoding,
) -> tuple:
    genes_tuple = None if genes is None else tuple(genes)
    genes_key = (
        None
        if genes_tuple is None
        else frozenset(str(g).upper() for g in genes_tuple)
    )
    cache_key = (
        genes_key,
        tuple(normalize) if isinstance(normalize, list) else normalize,
        bool(log_transform),
        bool(technical_rna_normalize),
        bool(remove_noncoding),
    )
    return cache_key, genes_tuple


@lru_cache(maxsize=None)
def _tcga_deconvolved_normalized(
    technical_rna_normalize: bool,
    remove_noncoding: bool,
) -> pd.DataFrame:
    """Build + validate the normalized TCGA-deconvolved frame once per worker.

    The normalize -> renormalize -> assert pipeline over the ~640k-row artifact
    costs ~3.5s and is a pure function of the (cached) raw read plus the two
    bool args, so memoize it — callers were re-running it on every call. The
    public wrapper returns a ``.copy()`` to keep the fresh-object contract.
    """
    df = _tcga_deconvolved_expression_cached().copy()
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=("cancer_code",),
        remove_noncoding=remove_noncoding,
    )
    df = _renormalize_long_groups_to_million(
        df,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=("cancer_code",),
    )
    assert_clean_tpm(
        df,
        value_cols=_DECONV_VALUE_COLS,
        label_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        context="tcga_deconvolved_expression",
    )
    return df


def tcga_deconvolved_expression(
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
) -> pd.DataFrame:
    """Per-(gene, TCGA code) tumor-only TPM medians from offline deconv.

    The current bundled artifact includes ``Ensembl_Gene_ID`` when it can be
    recovered unambiguously from the source reference. Historical rows for
    duplicated symbols remain symbol-keyed until the offline generator is rerun
    with the new ID-preserving schema. Trufflepig always exposes the artifact
    on the standard TPM-1e6 footing.
    """
    return _tcga_deconvolved_normalized(
        technical_rna_normalize, remove_noncoding
    ).copy()


@lru_cache(maxsize=None)
def _subtype_deconvolved_normalized(
    technical_rna_normalize: bool,
    remove_noncoding: bool,
) -> pd.DataFrame:
    """Build + validate the normalized subtype-deconvolved frame once per worker.

    Same rationale as :func:`_tcga_deconvolved_normalized`: the pipeline over the
    ~1.05M-row artifact costs ~5s and is pure in (raw read, bool args), so cache
    it instead of recomputing on every call.
    """
    df = _subtype_deconvolved_expression_cached().copy()
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="symbol",
        id_col=None,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=_SUBTYPE_GROUP_COLS,
        remove_noncoding=remove_noncoding,
    )
    df = _renormalize_long_groups_to_million(
        df,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=_SUBTYPE_GROUP_COLS,
    )
    assert_clean_tpm(
        df,
        value_cols=_DECONV_VALUE_COLS,
        label_col="symbol",
        id_col=None,
        context="subtype_deconvolved_expression",
    )
    return df


def subtype_deconvolved_expression(
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
) -> pd.DataFrame:
    """Per-(cancer_code, subtype, symbol) tumor-only TPM medians.

    Each (cancer_code, subtype) group is renormalized to the standard
    TPM-1e6 footing — trufflepig does not expose the native bundled scale.
    """
    return _subtype_deconvolved_normalized(
        technical_rna_normalize, remove_noncoding
    ).copy()


@lru_cache(maxsize=1)
def _cancer_reference_manifest_cached() -> pd.DataFrame:
    """Small artifact manifest without loading the 7+ GB summary frame.

    Oncoref's artifact build metadata and shard listing are the authoritative
    discovery surface for the artifact-backed expression accessor below. If
    those compact paths fail, degrade directly to registry-declared cohorts.
    Never invoke summary-row availability or pirlygenes' full canonical views.
    """
    availability_verified = False
    try:
        import oncoref

        manifest = _artifact_reference_manifest(oncoref)
        if "available" in manifest.columns:
            manifest = manifest[manifest["available"].fillna(False).astype(bool)]
        if (
            "n_reference_samples" in manifest.columns
            and "n_samples" in manifest.columns
        ):
            manifest = manifest.copy()
            n_samples = pd.to_numeric(manifest["n_samples"], errors="coerce")
            n_reference_samples = pd.to_numeric(
                manifest["n_reference_samples"], errors="coerce"
            )
            manifest["n_samples"] = n_samples.where(
                n_samples.notna(), n_reference_samples
            )
        if "cancer_code" not in manifest.columns:
            raise ValueError("cancer reference manifest has no cancer_code column")
        availability_verified = True
    except Exception:  # noqa: BLE001 - safe registry fallback is intentional
        manifest = pd.DataFrame(
            columns=[
                "cancer_code",
                "source_cohort",
                "processing_pipeline",
                "n_samples",
            ]
        )

    keep = [
        col
        for col in (
            "cancer_code",
            "source_cohort",
            "processing_pipeline",
            "n_samples",
        )
        if col in manifest.columns
    ]
    if "cancer_code" not in keep:
        raise ValueError("cancer reference manifest has no cancer_code column")
    manifest = manifest[keep].copy()

    # Registry provenance is a safe fallback only for rows that explicitly own
    # their cohort and classify against themselves. Parent-routed subtype rows
    # can carry an expression source/cohort for biological provenance without
    # having a physical clean-TPM artifact of their own (for example the MBL
    # molecular subgroups). Never advertise those as direct references.
    #
    # When oncoref's compact accessor succeeds, it is the complete authority for
    # the installed data bundle.  Do not merge registry aliases into verified
    # loader identities. When the accessor itself fails, the explicit
    # own-cohort/self-reference registry contract provides the lightweight
    # failover requested by discovery without loading expression.
    try:
        from .cancer_ontology import cancer_type_registry

        registry = cancer_type_registry()
        code = registry["code"].fillna("").astype(str).str.strip()
        source = registry["source_cohort"].fillna("").astype(str).str.strip()
        expression_source = (
            registry["expression_source"].fillna("").astype(str).str.strip().str.lower()
        )
        reference_source = (
            registry.get("reference_source", pd.Series("", index=registry.index))
            .fillna("")
            .astype(str)
            .str.strip()
            .str.lower()
        )
        classification_reference = (
            registry.get(
                "classification_reference_code",
                pd.Series("", index=registry.index),
            )
            .fillna("")
            .astype(str)
            .str.strip()
        )

        own = registry[
            ~expression_source.isin({"", "curated", "computed"})
            & source.ne("")
            & ~source.eq("LITERATURE_CURATED")
            & ~source.str.startswith("COMPUTED_")
            & reference_source.eq("own_cohort")
            & classification_reference.eq(code)
        ][["code", "source_cohort"]].rename(columns={"code": "cancer_code"})
        if not availability_verified:
            manifest = pd.concat([manifest, own], ignore_index=True, sort=False)
    except Exception:  # noqa: BLE001 - availability still works without registry merge
        pass

    # The public identity is (code, cohort). Prefer the most populated row for
    # each identity so both artifact metadata and registry fallback remain
    # one-row-per-loader-target even if an upstream table repeats an identity.
    identity_columns = ["cancer_code", "source_cohort"]
    if "source_cohort" not in manifest.columns:
        manifest["source_cohort"] = pd.NA
    for column in identity_columns:
        manifest[column] = manifest[column].astype("string").str.strip()
    metadata_columns = [
        column for column in manifest.columns if column not in identity_columns
    ]
    metadata_completeness = pd.Series(0, index=manifest.index, dtype="int64")
    for column in metadata_columns:
        values = manifest[column]
        populated = values.notna()
        if pd.api.types.is_string_dtype(values.dtype) or values.dtype == object:
            populated &= values.astype("string").str.strip().ne("").fillna(False)
        metadata_completeness += populated.astype("int64")
    manifest = manifest.assign(
        _manifest_metadata_completeness=metadata_completeness,
        _manifest_original_order=range(len(manifest)),
    )
    manifest = (
        manifest.sort_values(
            "_manifest_metadata_completeness",
            ascending=False,
            kind="stable",
        )
        .drop_duplicates(subset=identity_columns, keep="first")
        .sort_values("_manifest_original_order", kind="stable")
        .drop(
            columns=[
                "_manifest_metadata_completeness",
                "_manifest_original_order",
            ]
        )
        .reset_index(drop=True)
    )
    return manifest


def cancer_reference_manifest() -> pd.DataFrame:
    """Return one lightweight provenance row per observed reference cohort."""
    return _cancer_reference_manifest_cached().copy()


_CANCER_REFERENCE_MODE_ALIASES = {
    "tpm": "tpm",
    "tpm_raw": "tpm",
    "raw_tpm": "tpm",
    "tpm_clean": "tpm_clean",
    "clean_tpm": "tpm_clean",
    "tpm_log1p": "tpm_log1p",
    "tpm_raw_log1p": "tpm_log1p",
    "raw_tpm_log1p": "tpm_log1p",
    "tpm_clean_log1p": "tpm_clean_log1p",
    "clean_tpm_log1p": "tpm_clean_log1p",
    "tpm_clean_biological": "tpm_clean_biological",
    "clean_tpm_biological": "tpm_clean_biological",
    "biological_clean_tpm": "tpm_clean_biological",
}
_CANCER_REFERENCE_MODE_LABELS = {
    "tpm": "TPM",
    "tpm_clean": "TPM_clean",
    "tpm_log1p": "TPM_log1p",
    "tpm_clean_log1p": "TPM_clean_log1p",
    "tpm_clean_biological": "TPM_clean_biological",
}
_CANCER_REFERENCE_BACKEND_MODES = {
    "tpm": "tpm_raw",
    "tpm_clean": "tpm_clean",
    "tpm_log1p": "tpm_raw",
    "tpm_clean_log1p": "tpm_clean_log1p",
    "tpm_clean_biological": "tpm_clean_biological",
}
_CANCER_REFERENCE_BACKEND_WIDE_SUFFIXES = {
    "tpm": "TPM_raw",
    "tpm_clean": "TPM_clean",
    "tpm_log1p": "TPM_raw",
    "tpm_clean_log1p": "TPM_clean_log1p",
    "tpm_clean_biological": "TPM_clean_biological",
}
_RAW_REFERENCE_SUMMARY_DATASET = "cancer-reference-expression"
_RAW_REFERENCE_VALUE_COLUMNS = {
    "TPM_median": "expression",
    "TPM_q1": "q1",
    "TPM_q3": "q3",
}
_RAW_REFERENCE_SHARD_COLUMNS = {
    "Ensembl_Gene_ID",
    "Symbol",
    "cancer_code",
    "source_cohort",
    "source_project",
    "source_version",
    "TPM_median",
    "TPM_q1",
    "TPM_q3",
    "n_samples",
    "n_detected",
    "processing_pipeline",
    "notes",
    "tumor_origin",
    "metastasis_site",
}


def _cancer_reference_modes(normalize) -> list[str]:
    requested = [normalize] if isinstance(normalize, str) else list(normalize)
    modes: list[str] = []
    invalid: list[str] = []
    for value in requested:
        if not isinstance(value, str):
            invalid.append(repr(value))
            continue
        mode = _CANCER_REFERENCE_MODE_ALIASES.get(value.lower())
        if mode is None:
            invalid.append(repr(value))
        elif mode not in modes:
            modes.append(mode)
    if invalid:
        supported = ", ".join(sorted(_CANCER_REFERENCE_MODE_ALIASES))
        raise ValueError(
            f"unsupported cancer-reference normalization(s): {invalid}; "
            f"supported: {supported}"
        )
    return modes


def _raw_reference_shard_path(root, *, cancer_code: str, source_cohort: str):
    """Resolve one source-summary shard without opening the union artifact."""
    candidates = (
        root / f"{source_cohort}.csv.gz",
        root / f"{source_cohort}__{cancer_code}.csv.gz",
    )
    return next((path for path in candidates if path.is_file()), None)


def _bounded_raw_reference_expression(
    oncoref,
    *,
    cancer_types,
    genes,
    format: str,
    include_provenance: bool,
) -> pd.DataFrame:
    """Read raw TPM QC summaries from only the requested per-source shards.

    Oncoref's public source-union expression accessor currently materializes a
    roughly five-million-row frame before applying code/gene filters. Its
    compact availability accessor identifies the exact per-source CSV shards,
    so use that table as an index and read only those bounded files. These raw
    summaries intentionally use all source samples: they are the forensic QC
    companion to artifact-QC clean TPM, not another downstream analysis view.
    """
    import oncoref.expression as oncoref_expression

    availability = oncoref.cancer_reference_expression_availability(
        cancer_types=cancer_types,
        normalize="tpm_raw",
        sample_qc="all",
        reference_source="summary_rows_all",
        all_sources=True,
    )
    available = availability
    if "available" in available.columns:
        available = available[available["available"].fillna(False).astype(bool)]
    required_identity = {"cancer_code", "source_cohort"}
    if not required_identity.issubset(available.columns) or available.empty:
        out = _combine_cancer_reference_parts([], format=format)
        out.attrs["availability"] = availability.to_dict("records")
        out.attrs["missing_requests"] = availability.to_dict("records")
        out.attrs["reference_backend"] = "oncoref_bounded_summary_shards"
        return out

    # Wide output cannot encode source identity. Match oncoref's documented
    # richest-source selection policy, while long raw QC retains every source.
    if format == "wide":
        sort_columns = [
            column
            for column in ("n_reference_genes", "n_reference_samples")
            if column in available.columns
        ]
        if sort_columns:
            available = available.sort_values(
                sort_columns,
                ascending=[False] * len(sort_columns),
                kind="stable",
            )
        available = available.drop_duplicates(subset=["cancer_code"], keep="first")

    root = oncoref_expression._bundle_subdir(  # noqa: SLF001 - no public bounded reader
        _RAW_REFERENCE_SUMMARY_DATASET,
        auto_fetch=True,
    )
    pairs_by_path: dict[object, set[tuple[str, str]]] = {}
    for row in available.itertuples(index=False):
        code = str(row.cancer_code)
        source = str(row.source_cohort)
        path = _raw_reference_shard_path(
            root,
            cancer_code=code,
            source_cohort=source,
        )
        if path is not None:
            pairs_by_path.setdefault(path, set()).add((code, source))

    raw_parts: list[pd.DataFrame] = []
    for path, wanted_pairs in pairs_by_path.items():
        frame = pd.read_csv(
            path,
            usecols=lambda column: column in _RAW_REFERENCE_SHARD_COLUMNS,
            low_memory=False,
        )
        pair_index = pd.MultiIndex.from_frame(
            frame[["cancer_code", "source_cohort"]].astype(str)
        )
        frame = frame.loc[pair_index.isin(wanted_pairs)].copy()
        if frame.empty:
            continue
        frame = frame.loc[oncoref_expression._gene_filter_mask(frame, genes)].copy()
        if frame.empty:
            continue
        frame = oncoref_expression._apply_artifact_gene_universe(
            frame,
            product="cancer_reference_expression",
            cancer_codes=sorted({code for code, _source in wanted_pairs}),
            gene_universe="pirlygenes",
            include_gene_universe_flags=False,
        )
        frame = oncoref_expression._apply_gene_id_style(
            frame,
            product="cohort_gene_percentiles",
            cancer_codes=sorted({code for code, _source in wanted_pairs}),
            gene_id_style="pirlygenes",
            alias_expand_remaps=True,
        )
        raw_parts.append(frame)

    if raw_parts:
        raw = pd.concat(raw_parts, ignore_index=True, sort=False)
    else:
        raw = pd.DataFrame(
            columns=[
                "Ensembl_Gene_ID",
                "Symbol",
                "cancer_code",
                "source_cohort",
                *_RAW_REFERENCE_VALUE_COLUMNS,
            ]
        )

    # The availability artifact carries scale/QC provenance not repeated in
    # every expression row. Merge only missing fields to keep one source of
    # truth and avoid suffixing columns already present in the shard.
    identity = ["cancer_code", "source_cohort"]
    metadata_columns = [
        column
        for column in availability.columns
        if column not in raw.columns
        and column not in {"requested_code", "request_kind", "normalization", "available"}
    ]
    if not raw.empty and metadata_columns:
        metadata = available[[*identity, *metadata_columns]].drop_duplicates(identity)
        raw = raw.merge(metadata, on=identity, how="left", validate="many_to_one")

    raw = raw.rename(columns=_RAW_REFERENCE_VALUE_COLUMNS)
    raw["normalization"] = "tpm_raw"
    if format == "long":
        core = [
            "Ensembl_Gene_ID",
            "Symbol",
            "cancer_code",
            "normalization",
            "expression",
            "q1",
            "q3",
        ]
        source_identity = [
            column
            for column in ("source_cohort", "n_reference_samples", "n_samples", "n_detected")
            if column in raw.columns
        ]
        provenance = (
            [column for column in raw.columns if column not in {*core, *source_identity}]
            if include_provenance
            else []
        )
        out = raw[[*core[:-3], *source_identity, *provenance, *core[-3:]]].copy()
    else:
        value = raw[["Ensembl_Gene_ID", "Symbol", "cancer_code", "expression"]].copy()
        value["_column"] = value["cancer_code"].astype(str) + "_TPM_raw"
        out = value.pivot_table(
            index=["Ensembl_Gene_ID", "Symbol"],
            columns="_column",
            values="expression",
            aggfunc="first",
            sort=False,
        ).reset_index()
        out.columns.name = None

    out.attrs["availability"] = availability.to_dict("records")
    out.attrs["missing_requests"] = availability.loc[
        ~availability.get("available", pd.Series(True, index=availability.index))
        .fillna(False)
        .astype(bool)
    ].to_dict("records")
    out.attrs["reference_backend"] = "oncoref_bounded_summary_shards"
    out.attrs["sample_qc"] = "all"
    return out


def _adapt_cancer_reference_mode(
    frame: pd.DataFrame,
    *,
    mode: str,
    format: str,
) -> pd.DataFrame:
    """Restore pirlygenes-compatible labels and derive raw log1p safely."""
    out = frame.copy()
    label = _CANCER_REFERENCE_MODE_LABELS[mode]
    if format == "long":
        if mode == "tpm_log1p":
            for column in ("expression", "q1", "q3"):
                if column in out.columns:
                    out[column] = np.log1p(
                        pd.to_numeric(out[column], errors="coerce")
                    )
        if "normalization" in out.columns:
            out["normalization"] = label
    else:
        backend_suffix = _CANCER_REFERENCE_BACKEND_WIDE_SUFFIXES[mode]
        renamed = {}
        for column in out.columns:
            suffix = f"_{backend_suffix}"
            if not str(column).endswith(suffix):
                continue
            if mode == "tpm_log1p":
                out[column] = np.log1p(
                    pd.to_numeric(out[column], errors="coerce")
                )
            renamed[column] = f"{str(column)[: -len(suffix)]}_{label}"
        out = out.rename(columns=renamed)

    attrs = dict(frame.attrs)
    for attr_name in ("availability", "missing_requests"):
        if attr_name in attrs:
            attrs[attr_name] = [
                {**record, "normalization": label}
                for record in attrs[attr_name]
            ]
    transforms = list(attrs.get("compatibility_transforms", []))
    if mode == "tpm_log1p":
        transforms.append("tpm_log1p derived with numpy.log1p from raw TPM")
    attrs["compatibility_transforms"] = list(dict.fromkeys(transforms))
    attrs["reference_backend"] = frame.attrs.get(
        "reference_backend", "oncoref_artifact"
    )
    out.attrs = attrs
    return out


def _combine_cancer_reference_parts(
    parts: list[pd.DataFrame],
    *,
    format: str,
) -> pd.DataFrame:
    if not parts:
        if format == "long":
            return pd.DataFrame(columns=_CANCER_REFERENCE_EMPTY_COLUMNS)
        return pd.DataFrame(columns=["Ensembl_Gene_ID", "Symbol"])

    if format == "long":
        out = pd.concat(parts, ignore_index=True, sort=False)
    else:
        identifier_parts = [
            part[[column for column in ("Ensembl_Gene_ID", "Symbol") if column in part]]
            for part in parts
        ]
        identifiers = pd.concat(identifier_parts, ignore_index=True).drop_duplicates(
            subset=["Ensembl_Gene_ID"]
        )
        out = identifiers
        for part in parts:
            values = part.drop(columns=["Symbol"], errors="ignore")
            values = values.drop_duplicates(subset=["Ensembl_Gene_ID"])
            value_columns = [
                column for column in values.columns if column != "Ensembl_Gene_ID"
            ]
            out = out.merge(
                values[["Ensembl_Gene_ID", *value_columns]],
                on="Ensembl_Gene_ID",
                how="outer",
                sort=False,
            )

    attrs = dict(parts[0].attrs)
    for attr_name in ("availability", "missing_requests"):
        attrs[attr_name] = [
            record
            for part in parts
            for record in part.attrs.get(attr_name, [])
        ]
    attrs["compatibility_transforms"] = list(
        dict.fromkeys(
            transform
            for part in parts
            for transform in part.attrs.get("compatibility_transforms", [])
        )
    )
    backends = list(
        dict.fromkeys(
            str(part.attrs.get("reference_backend", "oncoref_artifact"))
            for part in parts
        )
    )
    attrs["reference_backend"] = (
        backends[0] if len(backends) == 1 else "+".join(backends)
    )
    out.attrs = attrs
    return out


def cancer_reference_expression(
    cancer_types=None,
    genes=None,
    normalize: str | list[str] | tuple[str, ...] = "tpm_clean",
    *,
    format: str = "long",
    include_provenance: bool = True,
) -> pd.DataFrame:
    """Observed tumor references from oncoref's bounded artifact paths.

    This is distinct from trufflepig's deconvolved tumor-cell references.
    Clean and log-clean modes read the shipped artifact-QC percentile shards.
    Raw TPM reads the shipped all-sample per-source summaries for forensic QC,
    and raw log1p is derived after the linear cohort summary. Thus callers can
    inspect raw values and use clean/log-clean values downstream without
    materializing the multi-gigabyte source-union frame or downloading the
    roughly 21 GB collection of per-sample source matrices.
    """
    import oncoref

    if format not in {"long", "wide"}:
        raise ValueError("format must be 'long' or 'wide'")
    modes = _cancer_reference_modes(normalize)
    cancer_types = (
        cancer_types
        if cancer_types is None or isinstance(cancer_types, str)
        else list(cancer_types)
    )
    genes = genes if genes is None or isinstance(genes, str) else list(genes)
    accessor = getattr(oncoref, "cancer_reference_expression", None)
    if accessor is None:
        if format == "long":
            return pd.DataFrame(columns=_CANCER_REFERENCE_EMPTY_COLUMNS)
        return pd.DataFrame(columns=["Ensembl_Gene_ID", "Symbol"])

    common_kwargs = {
        "genes": genes,
        "format": format,
        "include_provenance": include_provenance,
        "on_missing": "empty",
        "auto_fetch": False,
        "reference_source": "artifact",
        "gene_id_style": "pirlygenes",
        "gene_universe": "pirlygenes",
    }
    parts: list[pd.DataFrame] = []
    raw_backend: pd.DataFrame | None = None
    for mode in modes:
        backend_mode = _CANCER_REFERENCE_BACKEND_MODES[mode]
        if mode in {"tpm", "tpm_log1p"}:
            if raw_backend is None:
                raw_backend = _bounded_raw_reference_expression(
                    oncoref,
                    cancer_types=cancer_types,
                    genes=genes,
                    format=format,
                    include_provenance=include_provenance,
                )
            parts.append(
                _adapt_cancer_reference_mode(
                    raw_backend,
                    mode=mode,
                    format=format,
                )
            )
        else:
            frame = accessor(
                cancer_types=cancer_types,
                normalize=backend_mode,
                sample_qc="artifact",
                **common_kwargs,
            )
            parts.append(
                _adapt_cancer_reference_mode(frame, mode=mode, format=format)
            )

    df = _combine_cancer_reference_parts(parts, format=format)
    clean_requested = "tpm_clean" in modes
    if clean_requested and not df.empty:
        if format == "long":
            clean_rows = (
                df["normalization"].astype(str).str.lower().eq("tpm_clean")
                if "normalization" in df.columns
                else pd.Series(True, index=df.index)
            )
            value_cols = [col for col in ("expression", "q1", "q3") if col in df.columns]
            assert_clean_tpm(
                df.loc[clean_rows],
                value_cols=value_cols,
                context="cancer_reference_expression",
                technical_fraction=_CLEAN_TPM_V4_TECHNICAL_FRACTION,
            )
        else:
            value_cols = [col for col in df.columns if str(col).endswith("_TPM_clean")]
            assert_clean_tpm(
                df,
                value_cols=value_cols,
                context="cancer_reference_expression",
                technical_fraction=_CLEAN_TPM_V4_TECHNICAL_FRACTION,
            )
    return df


def pan_cancer_expression(
    genes=None,
    normalize=None,
    log_transform: bool = False,
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
) -> pd.DataFrame:
    """Expression across 50 normal tissues (nTPM) and 33 TCGA cancer types.

    Wraps :func:`pirlygenes.pan_cancer_expression` with trufflepig's
    TPM analysis view: raw TCGA/HPA TPM columns are retained only as
    explicit ``*_TPM_raw`` / ``*_nTPM_raw`` companions, clean columns are
    retained as ``*_TPM_clean`` / ``*_nTPM_clean``, and the analysis-facing
    ``*_TPM`` / ``*_nTPM`` aliases always point at the clean values.
    """
    cache_key, genes_tuple = _pan_cancer_cache_key(
        genes,
        normalize,
        log_transform,
        technical_rna_normalize,
        remove_noncoding,
    )
    cached = _PAN_CANCER_CACHE.get(cache_key)
    if cached is not None:
        return cached.copy()

    df = _load_pan_cancer_from_pirlygenes(
        genes_tuple=genes_tuple,
        remove_noncoding=remove_noncoding,
    )
    df = _standardize_pan_cancer_columns(df)
    # Collapse byte-identical-protein loci to the proteoform key space (SUM in
    # linear TPM/nTPM space — must precede any log/percentile transform). See
    # common.collapse_proteoform_loci. Sample conform + panels fold to match.
    from trufflepig.common import collapse_proteoform_loci

    wide_value_cols = _all_wide_tpm_value_cols(df)
    if wide_value_cols:
        df = collapse_proteoform_loci(df, value_cols=wide_value_cols)
    df = _apply_trufflepig_pan_normalize(df, normalize, log_transform)
    clean_companion_cols = _clean_companion_value_cols(df)
    if not clean_companion_cols:
        raise ValueError(
            "pirlygenes pan_cancer_expression did not provide clean TPM columns; "
            "trufflepig requires *_TPM_clean/*_nTPM_clean for analysis"
        )
    assert_clean_tpm(
        df,
        value_cols=clean_companion_cols,
        context="pan_cancer_expression",
    )
    _PAN_CANCER_CACHE[cache_key] = df
    return df.copy()


def cancer_types() -> list[str]:
    """Return the list of available TCGA cancer type codes (``<CODE>_TPM`` columns)."""
    df = pan_cancer_expression()
    return sorted(c.removesuffix("_TPM") for c in df.columns if c.endswith("_TPM"))


def cancer_expression(cancer_type, genes=None) -> pd.DataFrame:
    """Expression for a single cancer type as a simple gene-level DataFrame.

    Columns: ``Ensembl_Gene_ID``, ``Symbol``, ``expression``
    (housekeeping-normalized, technical-RNA-normalized).
    """
    from trufflepig.cancer_ontology import resolve_cancer_type

    code = resolve_cancer_type(cancer_type)
    df = pan_cancer_expression(
        genes=genes,
        normalize="housekeeping",
        technical_rna_normalize=True,
    )
    col = f"{code}_TPM"
    return df[["Ensembl_Gene_ID", "Symbol", col]].rename(columns={col: "expression"})


def cancer_enriched_genes(
    cancer_type,
    min_fold: float = 3.0,
    min_expression: float = 0.01,
) -> pd.DataFrame:
    """Genes enriched in one cancer type vs the median of all others."""
    from trufflepig.cancer_ontology import resolve_cancer_type

    code = resolve_cancer_type(cancer_type)
    df = pan_cancer_expression(normalize="housekeeping", technical_rna_normalize=True)
    target_col = f"{code}_TPM"
    if target_col not in df.columns:
        raise ValueError(
            f"Cancer type {cancer_type!r} -> {code!r} not in pan-cancer reference"
        )
    other_cols = [c for c in df.columns if c.endswith("_TPM") and c != target_col]
    target = df[target_col].astype(float)
    other_median = df[other_cols].astype(float).median(axis=1)
    fold = target / other_median.replace(0, float("nan"))
    keep = (fold >= min_fold) & (target >= min_expression)
    out = df.loc[keep, ["Ensembl_Gene_ID", "Symbol", target_col]].copy()
    out = out.rename(columns={target_col: "expression"})
    out["fold_over_others"] = fold[keep].values
    return out.sort_values("fold_over_others", ascending=False)


def top_enriched_per_cancer_type(
    top_n: int = 20,
    min_fold: float = 3.0,
    min_expression: float = 0.01,
) -> dict[str, pd.DataFrame]:
    """Top-N enriched genes per TCGA code (dict keyed by code)."""
    out: dict[str, pd.DataFrame] = {}
    for code in cancer_types():
        enriched = cancer_enriched_genes(
            code,
            min_fold=min_fold,
            min_expression=min_expression,
        )
        out[code] = enriched.head(top_n)
    return out


def tumor_up_vs_matched_normal(cancer_code: str | None = None) -> pd.DataFrame:
    """Solid-tumor genes dramatically up vs matched normal tissue."""
    return _filter_cancer_code(_tumor_up_vs_matched_normal_cached().copy(), cancer_code)


def heme_tumor_up_vs_matched_normal(cancer_code: str | None = None) -> pd.DataFrame:
    """Heme analogue of :func:`tumor_up_vs_matched_normal`."""
    return _filter_cancer_code(
        _heme_tumor_up_vs_matched_normal_cached().copy(),
        cancer_code,
    )


def hpa_cell_type_expression() -> pd.DataFrame:
    """Clean per-(gene, cell-type) nTPM from the HPA single-cell consensus."""
    return _hpa_cell_type_expression_cached().copy()


def estimate_signatures() -> pd.DataFrame:
    """ESTIMATE stromal / immune signature panels (Yoshihara 2013)."""
    return _pirlygenes.estimate_signatures()
