"""Expression-backed reference data for the analysis engine.

Pirlygenes owns the ID-keyed pan-cancer/HPA reference matrix and the
normalization primitives. Trufflepig owns deconvolved tumor-only
artifacts generated by its decomposition code. The public trufflepig
surface exposes normalized ``<CODE>_TPM`` cohort columns by default and
keeps symbol-level deconvolved references behind explicit accessors.
"""

from __future__ import annotations

from functools import lru_cache
from inspect import signature

import pandas as pd

import pirlygenes as _pirlygenes
from pirlygenes.load_dataset import get_data as get_reference_data

from ._data import TRUFFLEPIG_DATA_DIR
from .clean_tpm import assert_clean_tpm


_PAN_CANCER_CACHE: dict[tuple, pd.DataFrame] = {}
_TCGA_DECONV_PATH = TRUFFLEPIG_DATA_DIR / "tcga-deconvolved-expression.csv.gz"
_SUBTYPE_DECONV_PATH = TRUFFLEPIG_DATA_DIR / "subtype-deconvolved-expression.csv.gz"
_TUMOR_UP_MATCHED_NORMAL_PATH = TRUFFLEPIG_DATA_DIR / "tumor-up-vs-matched-normal.csv"
_HEME_TUMOR_UP_MATCHED_NORMAL_PATH = (
    TRUFFLEPIG_DATA_DIR / "heme-tumor-up-vs-matched-normal.csv"
)
_DECONV_VALUE_COLS = ("tumor_tpm_median", "tumor_tpm_q1", "tumor_tpm_q3")
_SUBTYPE_GROUP_COLS = ("cancer_code", "subtype")
_PIRLYGENES_PAN_PARAMS = signature(_pirlygenes.pan_cancer_expression).parameters
_PIRLYGENES_PAN_HAS_NORMALIZATION = "normalization" in _PIRLYGENES_PAN_PARAMS
_PIRLYGENES_PAN_HAS_NORMALIZE = "normalize" in _PIRLYGENES_PAN_PARAMS
_PIRLYGENES_VERSION = tuple(
    int(part)
    for part in str(getattr(_pirlygenes, "__version__", "0")).split(".")[:2]
    if part.isdigit()
)
_PIRLYGENES_PAN_HAS_NORMALIZE_PRESETS = (
    _PIRLYGENES_PAN_HAS_NORMALIZE and _PIRLYGENES_VERSION >= (5, 2)
)


def _parse_pan_value_column(col: str) -> tuple[str, int] | None:
    """Return ``(trufflepig_column, priority)`` for expression value columns.

    Trufflepig follows the pirlygenes 5.2 entity-first surface and keeps
    both raw and technical-RNA-clean views explicit:
    ``<tissue>_nTPM_raw`` / ``<cancer>_TPM_raw`` and
    ``<tissue>_nTPM_clean`` / ``<cancer>_TPM_clean``.
    """
    if col.startswith("tcga_"):
        return "", 0
    legacy_unit_prefixes = (
        "nTPM_clean_",
        "TPM_clean_",
        "nTPM_raw_",
        "TPM_raw_",
        "nTPM_",
        "TPM_",
        "FPKM_",
    )
    if col.startswith(legacy_unit_prefixes):
        raise ValueError(
            "pirlygenes returned a legacy unit-prefix expression column "
            f"{col!r}; trufflepig requires entity-first columns like "
            "'PRAD_TPM_clean'"
        )
    # Recognized normalized/provenance variants that should not leak through.
    drop_suffixes = (
        "_nTPM_hk",
        "_TPM_hk",
        "_nTPM_percentile",
        "_TPM_percentile",
        "_FPKM",
    )
    if col.endswith(drop_suffixes):
        return "", 0

    suffix_rules = (
        ("_nTPM_clean", "_nTPM_clean", 40),
        ("_TPM_clean", "_TPM_clean", 40),
        ("_nTPM_raw", "_nTPM_raw", 30),
        ("_TPM_raw", "_TPM_raw", 30),
        ("_nTPM", "_nTPM_raw", 20),
        ("_TPM", "_TPM_raw", 20),
    )
    for source_suffix, target_suffix, priority in suffix_rules:
        if col.endswith(source_suffix):
            return f"{col[: -len(source_suffix)]}{target_suffix}", priority
    return None


def _standardize_pan_cancer_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Convert pirlygenes' pan-cancer frame to trufflepig's stable schema."""
    selected: dict[str, tuple[int, str, int]] = {}
    non_value_cols: list[str] = []
    for position, col in enumerate(df.columns):
        parsed = _parse_pan_value_column(str(col))
        if parsed is None:
            non_value_cols.append(col)
            continue
        target, priority = parsed
        if not target:
            continue
        old = selected.get(target)
        if old is None or priority > old[0]:
            selected[target] = (priority, col, position)

    ordered_targets = sorted(selected, key=lambda target: selected[target][2])
    columns = {col: df[col] for col in non_value_cols}
    for target in ordered_targets:
        _priority, source, _position = selected[target]
        columns[target] = df[source]
    for target in ordered_targets:
        if target.endswith("_TPM_clean"):
            alias = target.removesuffix("_clean")
        elif target.endswith("_nTPM_clean"):
            alias = target.removesuffix("_clean")
        else:
            continue
        columns.setdefault(alias, df[selected[target][1]])
    return pd.DataFrame(columns, index=df.index).copy()


@lru_cache(maxsize=1)
def _tcga_deconvolved_expression_cached() -> pd.DataFrame:
    return pd.read_csv(_TCGA_DECONV_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _subtype_deconvolved_expression_cached() -> pd.DataFrame:
    return pd.read_csv(_SUBTYPE_DECONV_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _tumor_up_vs_matched_normal_cached() -> pd.DataFrame:
    return pd.read_csv(_TUMOR_UP_MATCHED_NORMAL_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _heme_tumor_up_vs_matched_normal_cached() -> pd.DataFrame:
    return pd.read_csv(_HEME_TUMOR_UP_MATCHED_NORMAL_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _hpa_cell_type_expression_cached() -> pd.DataFrame:
    df = _pirlygenes.hpa_cell_type_expression().copy()
    value_cols = [
        col
        for col in df.columns
        if col not in {"Ensembl_Gene_ID", "Symbol"}
        and pd.api.types.is_numeric_dtype(df[col])
    ]
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="Symbol",
        id_col="Ensembl_Gene_ID",
        value_cols=value_cols,
    )
    assert_clean_tpm(
        df,
        value_cols=value_cols,
        context="hpa_cell_type_expression",
    )
    return df


def _filter_cancer_code(df: pd.DataFrame, cancer_code: str | None) -> pd.DataFrame:
    if cancer_code is None:
        return df.reset_index(drop=True)
    code = str(cancer_code).upper()
    return df[df["cancer_code"].astype(str).str.upper() == code].reset_index(drop=True)


def _renormalize_long_groups_to_million(
    df: pd.DataFrame,
    *,
    value_cols: tuple[str, ...],
    group_cols: tuple[str, ...],
    reference_col: str | None = None,
) -> pd.DataFrame:
    out = df.copy()
    if not value_cols:
        return out
    reference_col = reference_col or value_cols[0]
    groupers = [out[col] for col in group_cols]
    reference_values = pd.to_numeric(out[reference_col], errors="coerce")
    totals = reference_values.groupby(groupers, dropna=False).transform("sum")
    mask = totals > 0
    scales = 1_000_000.0 / totals.where(mask)
    for col in value_cols:
        values = pd.to_numeric(out[col], errors="coerce")
        out[col] = values.where(~mask, values * scales)
    return out


def _analysis_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM", "_TPM"))
    ]


def _raw_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM_raw", "_TPM_raw"))
    ]


def _clean_companion_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM_clean", "_TPM_clean"))
    ]


def _all_wide_tpm_value_cols(df: pd.DataFrame) -> list[str]:
    return _raw_value_cols(df) + _clean_companion_value_cols(df) + _analysis_value_cols(df)


def _renormalize_wide_to_million(df: pd.DataFrame) -> pd.DataFrame:
    value_cols = _all_wide_tpm_value_cols(df)
    out, _ = _pirlygenes.renormalize_to_million(df, value_cols=value_cols)
    return out


def _apply_trufflepig_pan_normalize(
    df: pd.DataFrame,
    normalize,
    log_transform: bool,
) -> pd.DataFrame:
    value_cols = _analysis_value_cols(df)
    if isinstance(normalize, (list, tuple, set)):
        modes = {str(mode).lower() for mode in normalize}
        if modes <= {"tpm", "tpm_clean"}:
            normalize = "tpm_clean"
        elif "housekeeping" in modes or "hk" in modes:
            normalize = "housekeeping"
        elif "percentile" in modes:
            normalize = "percentile"
    if normalize is None or normalize in {"tpm", "TPM", "tpm_clean"}:
        out = df
    elif normalize in {"housekeeping", "hk"}:
        out = _pirlygenes.normalize_to_housekeeping(df, value_cols=value_cols)
    elif normalize == "percentile":
        out, _ = _pirlygenes.percentile_rank_expression(df, value_cols=value_cols)
    else:
        raise ValueError(
            "normalize must be None, 'tpm', 'tpm_clean', 'housekeeping', "
            "'hk', or 'percentile'; "
            f"got {normalize!r}"
        )
    if log_transform:
        out = _pirlygenes.log2_transform(out, value_cols=value_cols)
    return out


def _load_pan_cancer_from_pirlygenes(
    *,
    genes_tuple,
    normalize,
    log_transform: bool,
    technical_rna_normalize: bool,
    remove_noncoding: bool,
) -> pd.DataFrame:
    del log_transform
    del technical_rna_normalize
    if _PIRLYGENES_PAN_HAS_NORMALIZE_PRESETS:
        if remove_noncoding:
            return _pirlygenes.pan_cancer_expression(
                genes=genes_tuple,
                normalize=["tpm", "tpm_clean"],
                technical_rna_normalize=True,
                remove_noncoding=True,
                renormalize_to_million=True,
            )
        return _pirlygenes.pan_cancer_expression(
            genes=genes_tuple,
            normalize=["tpm", "tpm_clean"],
        )

    if _PIRLYGENES_PAN_HAS_NORMALIZATION:
        return _pirlygenes.pan_cancer_expression(
            genes=genes_tuple,
            normalization="clean_tpm",
            remove_noncoding=remove_noncoding,
        )

    return _pirlygenes.pan_cancer_expression(
        genes=genes_tuple,
        normalize=None,
        log_transform=False,
        technical_rna_normalize=True,
        remove_noncoding=remove_noncoding,
        renormalize_to_million=True,
    )


def _pan_cancer_cache_key(
    genes,
    normalize,
    log_transform,
    technical_rna_normalize,
    remove_noncoding,
    renormalize_to_million,
) -> tuple:
    genes_tuple = None if genes is None else tuple(genes)
    genes_key = (
        None
        if genes_tuple is None
        else frozenset(str(g).upper() for g in genes_tuple)
    )
    cache_key = (
        genes_key,
        tuple(normalize) if isinstance(normalize, list) else normalize,
        bool(log_transform),
        bool(technical_rna_normalize),
        bool(remove_noncoding),
        bool(renormalize_to_million),
    )
    return cache_key, genes_tuple


def tcga_deconvolved_expression(
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
    renormalize_to_million: bool = True,
) -> pd.DataFrame:
    """Per-(gene, TCGA code) tumor-only TPM medians from offline deconv.

    The current bundled artifact includes ``Ensembl_Gene_ID`` when it can be
    recovered unambiguously from the source reference. Historical rows for
    duplicated symbols remain symbol-keyed until the offline generator is rerun
    with the new ID-preserving schema. Trufflepig exposes the artifact on the
    standard TPM-1e6 footing by default.
    """
    if not renormalize_to_million:
        raise ValueError(
            "trufflepig exposes normalized TPM-scale references only; "
            "renormalize_to_million=False is no longer supported"
        )
    df = _tcga_deconvolved_expression_cached().copy()
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=("cancer_code",),
        remove_noncoding=remove_noncoding,
    )
    df = _renormalize_long_groups_to_million(
        df,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=("cancer_code",),
    )
    assert_clean_tpm(
        df,
        value_cols=_DECONV_VALUE_COLS,
        label_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        context="tcga_deconvolved_expression",
    )
    return df


def subtype_deconvolved_expression(
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
    renormalize_to_million: bool = True,
) -> pd.DataFrame:
    """Per-(cancer_code, subtype, symbol) tumor-only TPM medians.

    Trufflepig surface flips ``renormalize_to_million`` to ``True`` so
    each (cancer_code, subtype) group is on the standard TPM-1e6
    footing. Trufflepig no longer exposes the native bundled scale.
    """
    if not renormalize_to_million:
        raise ValueError(
            "trufflepig exposes normalized TPM-scale references only; "
            "renormalize_to_million=False is no longer supported"
        )
    df = _subtype_deconvolved_expression_cached().copy()
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="symbol",
        id_col=None,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=_SUBTYPE_GROUP_COLS,
        remove_noncoding=remove_noncoding,
    )
    df = _renormalize_long_groups_to_million(
        df,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=_SUBTYPE_GROUP_COLS,
    )
    assert_clean_tpm(
        df,
        value_cols=_DECONV_VALUE_COLS,
        label_col="symbol",
        id_col=None,
        context="subtype_deconvolved_expression",
    )
    return df


def pan_cancer_expression(
    genes=None,
    normalize=None,
    log_transform: bool = False,
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
    renormalize_to_million: bool = True,
) -> pd.DataFrame:
    """Expression across 50 normal tissues (nTPM) and 33 TCGA cancer types.

    Wraps :func:`pirlygenes.pan_cancer_expression` with trufflepig's
    TPM analysis view: raw TCGA/HPA TPM columns are retained only as
    explicit ``*_TPM_raw`` / ``*_nTPM_raw`` companions, clean columns are
    retained as ``*_TPM_clean`` / ``*_nTPM_clean``, and the analysis-facing
    ``*_TPM`` / ``*_nTPM`` aliases always point at the clean values.
    """
    if not renormalize_to_million:
        raise ValueError(
            "trufflepig exposes normalized TPM-scale references only; "
            "renormalize_to_million=False is no longer supported"
        )
    cache_key, genes_tuple = _pan_cancer_cache_key(
        genes,
        normalize,
        log_transform,
        technical_rna_normalize,
        remove_noncoding,
        True,
    )
    cached = _PAN_CANCER_CACHE.get(cache_key)
    if cached is not None:
        return cached.copy()

    df = _load_pan_cancer_from_pirlygenes(
        genes_tuple=genes_tuple,
        normalize=normalize,
        log_transform=log_transform,
        technical_rna_normalize=technical_rna_normalize,
        remove_noncoding=remove_noncoding,
    )
    df = _standardize_pan_cancer_columns(df)
    df = _apply_trufflepig_pan_normalize(df, normalize, log_transform)
    clean_companion_cols = _clean_companion_value_cols(df)
    if not clean_companion_cols:
        raise ValueError(
            "pirlygenes pan_cancer_expression did not provide clean TPM columns; "
            "trufflepig requires *_TPM_clean/*_nTPM_clean for analysis"
        )
    clean_cols = clean_companion_cols + _analysis_value_cols(df)
    assert_clean_tpm(
        df,
        value_cols=clean_cols,
        context="pan_cancer_expression",
    )
    _PAN_CANCER_CACHE[cache_key] = df
    return df.copy()


def cancer_types() -> list[str]:
    """Return the list of available TCGA cancer type codes (``<CODE>_TPM`` columns)."""
    df = pan_cancer_expression()
    return sorted(c.removesuffix("_TPM") for c in df.columns if c.endswith("_TPM"))


def cancer_expression(cancer_type, genes=None) -> pd.DataFrame:
    """Expression for a single cancer type as a simple gene-level DataFrame.

    Columns: ``Ensembl_Gene_ID``, ``Symbol``, ``expression``
    (housekeeping-normalized, technical-RNA-normalized).
    """
    from pirlygenes.gene_sets_cancer import resolve_cancer_type

    code = resolve_cancer_type(cancer_type)
    df = pan_cancer_expression(
        genes=genes,
        normalize="housekeeping",
        technical_rna_normalize=True,
    )
    col = f"{code}_TPM"
    return df[["Ensembl_Gene_ID", "Symbol", col]].rename(columns={col: "expression"})


def cancer_enriched_genes(
    cancer_type,
    min_fold: float = 3.0,
    min_expression: float = 0.01,
) -> pd.DataFrame:
    """Genes enriched in one cancer type vs the median of all others."""
    from pirlygenes.gene_sets_cancer import resolve_cancer_type

    code = resolve_cancer_type(cancer_type)
    df = pan_cancer_expression(normalize="housekeeping", technical_rna_normalize=True)
    target_col = f"{code}_TPM"
    if target_col not in df.columns:
        raise ValueError(
            f"Cancer type {cancer_type!r} -> {code!r} not in pan-cancer reference"
        )
    other_cols = [c for c in df.columns if c.endswith("_TPM") and c != target_col]
    target = df[target_col].astype(float)
    other_median = df[other_cols].astype(float).median(axis=1)
    fold = target / other_median.replace(0, float("nan"))
    keep = (fold >= min_fold) & (target >= min_expression)
    out = df.loc[keep, ["Ensembl_Gene_ID", "Symbol", target_col]].copy()
    out = out.rename(columns={target_col: "expression"})
    out["fold_over_others"] = fold[keep].values
    return out.sort_values("fold_over_others", ascending=False)


def top_enriched_per_cancer_type(
    top_n: int = 20,
    min_fold: float = 3.0,
    min_expression: float = 0.01,
) -> dict[str, pd.DataFrame]:
    """Top-N enriched genes per TCGA code (dict keyed by code)."""
    out: dict[str, pd.DataFrame] = {}
    for code in cancer_types():
        enriched = cancer_enriched_genes(
            code,
            min_fold=min_fold,
            min_expression=min_expression,
        )
        out[code] = enriched.head(top_n)
    return out


def tumor_up_vs_matched_normal(cancer_code: str | None = None) -> pd.DataFrame:
    """Solid-tumor genes dramatically up vs matched normal tissue."""
    return _filter_cancer_code(_tumor_up_vs_matched_normal_cached().copy(), cancer_code)


def heme_tumor_up_vs_matched_normal(cancer_code: str | None = None) -> pd.DataFrame:
    """Heme analogue of :func:`tumor_up_vs_matched_normal`."""
    return _filter_cancer_code(
        _heme_tumor_up_vs_matched_normal_cached().copy(),
        cancer_code,
    )


def hpa_cell_type_expression() -> pd.DataFrame:
    """Clean per-(gene, cell-type) nTPM from the HPA single-cell consensus."""
    return _hpa_cell_type_expression_cached().copy()


def estimate_signatures() -> pd.DataFrame:
    """ESTIMATE stromal / immune signature panels (Yoshihara 2013)."""
    return _pirlygenes.estimate_signatures()
