"""Expression-backed reference data for the analysis engine.

Pirlygenes owns the ID-keyed pan-cancer/HPA reference matrix and the
normalization primitives. Trufflepig owns deconvolved tumor-only
artifacts generated by its decomposition code. The public trufflepig
surface exposes normalized ``<CODE>_TPM`` cohort columns by default and
keeps symbol-level deconvolved references behind explicit accessors.
"""

from __future__ import annotations

from functools import lru_cache
from inspect import signature

import pandas as pd
import pirlygenes as _pirlygenes
from pirlygenes.expression.qc import TECHNICAL_FRACTION

from ._data import TRUFFLEPIG_DATA_DIR
from .clean_tpm import assert_clean_tpm

# pirlygenes clean TPM pins the censored (technical-RNA + ribosomal) compartment
# to this fraction of the 1e6 budget — split into separately-pinned ribosomal
# (~16%) and other-technical (~9%) sub-compartments — rather than zeroing it.
# Import the PUBLIC pirlygenes constant so the guard tracks the value pirlygenes
# actually applies (surviving any future change) instead of a hardcoded copy.
_CLEAN_TPM_V4_TECHNICAL_FRACTION = TECHNICAL_FRACTION

_PAN_CANCER_CACHE: dict[tuple, pd.DataFrame] = {}
_TCGA_DECONV_PATH = TRUFFLEPIG_DATA_DIR / "tcga-deconvolved-expression.csv.gz"
_SUBTYPE_DECONV_PATH = TRUFFLEPIG_DATA_DIR / "subtype-deconvolved-expression.csv.gz"
_TUMOR_UP_MATCHED_NORMAL_PATH = TRUFFLEPIG_DATA_DIR / "tumor-up-vs-matched-normal.csv"
_HEME_TUMOR_UP_MATCHED_NORMAL_PATH = (
    TRUFFLEPIG_DATA_DIR / "heme-tumor-up-vs-matched-normal.csv"
)
_DECONV_VALUE_COLS = ("tumor_tpm_median", "tumor_tpm_q1", "tumor_tpm_q3")
_SUBTYPE_GROUP_COLS = ("cancer_code", "subtype")
_CANCER_REFERENCE_EMPTY_COLUMNS = [
    "Ensembl_Gene_ID",
    "Symbol",
    "cancer_code",
    "source_cohort",
    "source_project",
    "source_version",
    "n_samples",
    "n_detected",
    "processing_pipeline",
    "notes",
    "normalization",
    "expression",
    "q1",
    "q3",
]


def _all_source_reference_availability(
    oncoref,
    public_accessor,
    default_manifest: pd.DataFrame,
) -> pd.DataFrame:
    """Expand oncoref's one-source-per-code view through exact source filters.

    ``summary_rows_all`` can load several source cohorts for one cancer code,
    while the availability accessor currently returns only one provenance row
    per code (oncoref#393). The public cohort registry gives us the finite set
    of source identities, and the availability accessor can cheaply verify each
    one without loading expression values.

    oncoref 1.8.129 applies ``source_cohort`` to availability but reports the
    unfiltered default source in the provenance columns. Treat the requested
    cohort as authoritative only for rows that the filtered call marks
    available, and discard metadata that belongs to the mismatched source.
    """
    try:
        if "source_cohort" not in signature(public_accessor).parameters:
            return default_manifest
        cohort_registry_accessor = getattr(oncoref, "cohort_registry_df", None)
        if not callable(cohort_registry_accessor):
            return default_manifest
        cohort_registry = cohort_registry_accessor()
        if "cohort_id" not in cohort_registry.columns:
            return default_manifest
        registered_source_cohorts = (
            cohort_registry["cohort_id"]
            .dropna()
            .astype(str)
            .str.strip()
            .loc[lambda values: values.ne("")]
            .drop_duplicates()
            .tolist()
        )
        default_source_cohorts = (
            default_manifest["source_cohort"]
            .dropna()
            .astype(str)
            .str.strip()
            .loc[lambda values: values.ne("")]
            .drop_duplicates()
            .tolist()
            if "source_cohort" in default_manifest.columns
            else []
        )
        source_cohorts = list(
            dict.fromkeys(
                [*registered_source_cohorts, *default_source_cohorts]
            )
        )
    except Exception:  # noqa: BLE001 - retain the verified default view
        return default_manifest

    source_manifests: list[pd.DataFrame] = []
    for source_cohort in source_cohorts:
        try:
            filtered = public_accessor(
                normalize="tpm_clean",
                reference_source="summary_rows_all",
                sample_qc="all",
                source_cohort=source_cohort,
            )
        except Exception:  # noqa: BLE001 - one bad source must not hide the rest
            continue
        if "cancer_code" not in filtered.columns:
            continue
        if "available" in filtered.columns:
            filtered = filtered[
                filtered["available"].fillna(False).astype(bool)
            ]
        if filtered.empty:
            continue

        filtered = filtered.copy()
        reported_source = filtered.get(
            "source_cohort",
            pd.Series(pd.NA, index=filtered.index, dtype="string"),
        ).astype("string")
        provenance_mismatch = reported_source.fillna("").str.strip().ne(
            source_cohort
        )
        # ``source_cohort`` is a loader identity, not merely a display label.
        # Keep the exact key whose filtered availability was verified even
        # when oncoref reports a different default/provenance name.  In
        # oncoref 1.8.129 this distinction is load-bearing for the DDLPS and
        # WDLPS Treehouse references: ``...TCGA_SUBSET`` loads expression,
        # while the reported ``...TCGA_SARC_HISTOLOGY`` alias does not.
        filtered["source_cohort"] = source_cohort
        # Affected oncoref releases select availability with the requested
        # source but populate provenance from the default source. Identity is
        # still verified; source-specific counts/pipeline are not.
        for column in (
            "n_reference_samples",
            "n_samples",
            "processing_pipeline",
        ):
            if column in filtered.columns:
                filtered.loc[provenance_mismatch, column] = pd.NA
        source_manifests.append(filtered)

    # Exact-source expansion is authoritative when it yields rows.  The
    # unfiltered oncoref 1.8.129 view can report compatibility/default aliases
    # that the expression loader cannot consume (for example MTC without its
    # ``_MTC`` cohort suffix).  Retain a default row only when its identity is
    # already verified or when the code has exactly one verified source, in
    # which case the canonical identity is unambiguous and its richer default
    # metadata can be preserved.
    if not source_manifests:
        return default_manifest
    columns = list(
        dict.fromkeys(
            column
            for source_manifest in source_manifests
            for column in source_manifest.columns
        )
    )
    records = [
        record
        for source_manifest in source_manifests
        for record in source_manifest.to_dict("records")
    ]
    exact_manifest = pd.DataFrame.from_records(records, columns=columns)
    exact_sources_by_code = (
        exact_manifest[["cancer_code", "source_cohort"]]
        .dropna()
        .astype(str)
        .groupby("cancer_code")["source_cohort"]
        .agg(lambda values: frozenset(values))
        .to_dict()
    )
    if not {"cancer_code", "source_cohort"}.issubset(default_manifest.columns):
        return exact_manifest

    reconciled_defaults = default_manifest.copy()
    keep_default = pd.Series(False, index=reconciled_defaults.index)
    for index, row in reconciled_defaults.iterrows():
        code_value = row.get("cancer_code")
        source_value = row.get("source_cohort")
        code = "" if pd.isna(code_value) else str(code_value).strip()
        source = "" if pd.isna(source_value) else str(source_value).strip()
        verified_sources = exact_sources_by_code.get(code, frozenset())
        if source in verified_sources:
            canonical_source = source
        elif len(verified_sources) == 1:
            canonical_source = next(iter(verified_sources))
        else:
            continue
        reconciled_defaults.at[index, "source_cohort"] = canonical_source
        keep_default.at[index] = True

    reconciled_defaults = reconciled_defaults.loc[keep_default]
    combined = [reconciled_defaults, exact_manifest]
    combined_columns = list(
        dict.fromkeys(
            column for frame in combined for column in frame.columns
        )
    )
    combined_records = [
        record
        for frame in combined
        for record in frame.to_dict("records")
    ]
    return pd.DataFrame.from_records(
        combined_records,
        columns=combined_columns,
    )


def _parse_pan_value_column(col: str) -> tuple[str, int] | None:
    """Return ``(trufflepig_column, priority)`` for expression value columns.

    Trufflepig follows the pirlygenes 5.2 entity-first surface and keeps
    both raw and technical-RNA-clean views explicit:
    ``<tissue>_nTPM_raw`` / ``<cancer>_TPM_raw`` and
    ``<tissue>_nTPM_clean`` / ``<cancer>_TPM_clean``.
    """
    if col.startswith("tcga_"):
        return "", 0
    legacy_unit_prefixes = (
        "nTPM_clean_",
        "TPM_clean_",
        "nTPM_raw_",
        "TPM_raw_",
        "nTPM_",
        "TPM_",
        "FPKM_",
    )
    if col.startswith(legacy_unit_prefixes):
        raise ValueError(
            "pirlygenes returned a legacy unit-prefix expression column "
            f"{col!r}; trufflepig requires entity-first columns like "
            "'PRAD_TPM_clean'"
        )
    # Recognized normalized/provenance variants that should not leak through.
    drop_suffixes = (
        "_nTPM_hk",
        "_TPM_hk",
        "_nTPM_percentile",
        "_TPM_percentile",
        "_FPKM",
    )
    if col.endswith(drop_suffixes):
        return "", 0

    suffix_rules = (
        ("_nTPM_clean", "_nTPM_clean", 40),
        ("_TPM_clean", "_TPM_clean", 40),
        ("_nTPM_raw", "_nTPM_raw", 30),
        ("_TPM_raw", "_TPM_raw", 30),
        ("_nTPM", "_nTPM_raw", 20),
        ("_TPM", "_TPM_raw", 20),
    )
    for source_suffix, target_suffix, priority in suffix_rules:
        if col.endswith(source_suffix):
            return f"{col[: -len(source_suffix)]}{target_suffix}", priority
    return None


def _standardize_pan_cancer_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Convert pirlygenes' pan-cancer frame to trufflepig's stable schema."""
    selected: dict[str, tuple[int, str, int]] = {}
    non_value_cols: list[str] = []
    for position, col in enumerate(df.columns):
        parsed = _parse_pan_value_column(str(col))
        if parsed is None:
            non_value_cols.append(col)
            continue
        target, priority = parsed
        if not target:
            continue
        old = selected.get(target)
        if old is None or priority > old[0]:
            selected[target] = (priority, col, position)

    ordered_targets = sorted(selected, key=lambda target: selected[target][2])
    columns = {col: df[col] for col in non_value_cols}
    for target in ordered_targets:
        _priority, source, _position = selected[target]
        columns[target] = df[source]
    # Analysis-facing aliases (`*_TPM`, `*_nTPM`) intentionally shadow the
    # "raw" semantics they had under pirlygenes 5.1 — they now point at the
    # technical-RNA-clean columns so every analysis path sees the same
    # sanitized values. Callers that need raw must read `*_TPM_raw` /
    # `*_nTPM_raw` explicitly.
    for target in ordered_targets:
        if target.endswith("_TPM_clean"):
            alias = target.removesuffix("_clean")
        elif target.endswith("_nTPM_clean"):
            alias = target.removesuffix("_clean")
        else:
            continue
        columns.setdefault(alias, df[selected[target][1]])
    return pd.DataFrame(columns, index=df.index).copy()


def _canonicalize_cancer_code_column(df: pd.DataFrame) -> pd.DataFrame:
    """Resolve the ``cancer_code`` column through pirlygenes' alias resolver.

    The bundled deconvolved artifacts predate pirlygenes' Phase-C code renames
    (e.g. ``CHON``→``SARC_CHON``), so a sample looked up by its *new* registry
    code would silently miss its subtype reference and fall back to broad SARC.
    Canonicalizing on load — using the now-shipped ``CANCER_TYPE_ALIASES`` — keeps
    the artifact correct without a regeneration and auto-absorbs future rename
    waves. Codes with no alias (legacy cohort-name leakage like ``BEATAML`` /
    ``TARGET_*``, a separate data-gen issue) are left unchanged. See #53.
    """
    if "cancer_code" not in df.columns:
        return df
    from trufflepig.cancer_ontology import resolve_cancer_type

    def _resolve(code: str) -> str:
        try:
            return resolve_cancer_type(code)
        except Exception:
            return code

    uniques = df["cancer_code"].dropna().astype(str).unique()
    mapping = {code: _resolve(code) for code in uniques}
    df["cancer_code"] = df["cancer_code"].map(
        lambda c: mapping.get(str(c), c) if pd.notna(c) else c
    )
    return df


@lru_cache(maxsize=1)
def _tcga_deconvolved_expression_cached() -> pd.DataFrame:
    df = pd.read_csv(_TCGA_DECONV_PATH, low_memory=False)
    df = _canonicalize_cancer_code_column(df)
    # Relabel byte-identical-protein members to the proteoform id BEFORE the
    # normalize→renormalize-to-1e6 pipeline, so the per-cancer TPM-1e6 invariant
    # is preserved after the member rows are folded out (see
    # common.relabel_proteoform_symbols_long — medians are not summed, the
    # dominant-locus row is kept; true summation belongs to the upstream generator).
    from trufflepig.common import relabel_proteoform_symbols_long

    return relabel_proteoform_symbols_long(
        df,
        symbol_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        dedup_keys=("symbol", "cancer_code"),
        value_col="tumor_tpm_median",
    )


@lru_cache(maxsize=1)
def _subtype_deconvolved_expression_cached() -> pd.DataFrame:
    df = pd.read_csv(_SUBTYPE_DECONV_PATH, low_memory=False)
    df = _canonicalize_cancer_code_column(df)
    from trufflepig.common import relabel_proteoform_symbols_long

    return relabel_proteoform_symbols_long(
        df,
        symbol_col="symbol",
        dedup_keys=("symbol", "cancer_code", "subtype", "source_cohort"),
        value_col="tumor_tpm_median",
    )


@lru_cache(maxsize=1)
def _tumor_up_vs_matched_normal_cached() -> pd.DataFrame:
    return pd.read_csv(_TUMOR_UP_MATCHED_NORMAL_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _heme_tumor_up_vs_matched_normal_cached() -> pd.DataFrame:
    return pd.read_csv(_HEME_TUMOR_UP_MATCHED_NORMAL_PATH, low_memory=False)


@lru_cache(maxsize=1)
def _hpa_cell_type_expression_cached() -> pd.DataFrame:
    df = _pirlygenes.hpa_cell_type_expression().copy()
    value_cols = [
        col
        for col in df.columns
        if col not in {"Ensembl_Gene_ID", "Symbol"}
        and pd.api.types.is_numeric_dtype(df[col])
    ]
    # Proteoform-collapse (SUM) the linear cell-type nTPM matrix before normalize.
    from trufflepig.common import collapse_proteoform_loci

    if value_cols:
        df = collapse_proteoform_loci(df, value_cols=value_cols)
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="Symbol",
        id_col="Ensembl_Gene_ID",
        value_cols=value_cols,
    )
    assert_clean_tpm(
        df,
        value_cols=value_cols,
        context="hpa_cell_type_expression",
    )
    return df


def _filter_cancer_code(df: pd.DataFrame, cancer_code: str | None) -> pd.DataFrame:
    if cancer_code is None:
        return df.reset_index(drop=True)
    code = str(cancer_code).upper()
    return df[df["cancer_code"].astype(str).str.upper() == code].reset_index(drop=True)


def _renormalize_long_groups_to_million(
    df: pd.DataFrame,
    *,
    value_cols: tuple[str, ...],
    group_cols: tuple[str, ...],
    reference_col: str | None = None,
) -> pd.DataFrame:
    out = df.copy()
    if not value_cols:
        return out
    reference_col = reference_col or value_cols[0]
    groupers = [out[col] for col in group_cols]
    reference_values = pd.to_numeric(out[reference_col], errors="coerce")
    totals = reference_values.groupby(groupers, dropna=False).transform("sum")
    mask = totals > 0
    scales = 1_000_000.0 / totals.where(mask)
    for col in value_cols:
        values = pd.to_numeric(out[col], errors="coerce")
        out[col] = values.where(~mask, values * scales)
    return out


def _analysis_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM", "_TPM"))
    ]


def _raw_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM_raw", "_TPM_raw"))
    ]


def _clean_companion_value_cols(df: pd.DataFrame) -> list[str]:
    return [
        col
        for col in df.columns
        if str(col).endswith(("_nTPM_clean", "_TPM_clean"))
    ]


def _all_wide_tpm_value_cols(df: pd.DataFrame) -> list[str]:
    return _raw_value_cols(df) + _clean_companion_value_cols(df) + _analysis_value_cols(df)


def _apply_trufflepig_pan_normalize(
    df: pd.DataFrame,
    normalize,
    log_transform: bool,
) -> pd.DataFrame:
    value_cols = _analysis_value_cols(df)
    if isinstance(normalize, (list, tuple, set)):
        modes = {str(mode).lower() for mode in normalize}
        if modes <= {"tpm", "tpm_clean"}:
            normalize = "tpm_clean"
        elif "housekeeping" in modes or "hk" in modes:
            normalize = "housekeeping"
        elif "percentile" in modes:
            normalize = "percentile"
    if normalize is None or normalize in {"tpm", "TPM", "tpm_clean"}:
        out = df
    elif normalize in {"housekeeping", "hk"}:
        out = _pirlygenes.normalize_to_housekeeping(df, value_cols=value_cols)
    elif normalize == "percentile":
        out, _ = _pirlygenes.percentile_rank_expression(df, value_cols=value_cols)
    else:
        raise ValueError(
            "normalize must be None, 'tpm', 'tpm_clean', 'housekeeping', "
            "'hk', or 'percentile'; "
            f"got {normalize!r}"
        )
    if log_transform:
        out = _pirlygenes.log2_transform(out, value_cols=value_cols)
    return out


def _load_pan_cancer_from_pirlygenes(
    *,
    genes_tuple,
    remove_noncoding: bool,
) -> pd.DataFrame:
    # Trufflepig pins pirlygenes>=5.2,<6 (see pyproject.toml), which provides
    # the entity-first ``normalize=["tpm", "tpm_clean"]`` preset and clean
    # TPM columns by default. Earlier pirlygenes APIs are not supported.
    if remove_noncoding:
        return _pirlygenes.pan_cancer_expression(
            genes=genes_tuple,
            normalize=["tpm", "tpm_clean"],
            technical_rna_normalize=True,
            remove_noncoding=True,
            renormalize_to_million=True,
        )
    return _pirlygenes.pan_cancer_expression(
        genes=genes_tuple,
        normalize=["tpm", "tpm_clean"],
    )


def _pan_cancer_cache_key(
    genes,
    normalize,
    log_transform,
    technical_rna_normalize,
    remove_noncoding,
) -> tuple:
    genes_tuple = None if genes is None else tuple(genes)
    genes_key = (
        None
        if genes_tuple is None
        else frozenset(str(g).upper() for g in genes_tuple)
    )
    cache_key = (
        genes_key,
        tuple(normalize) if isinstance(normalize, list) else normalize,
        bool(log_transform),
        bool(technical_rna_normalize),
        bool(remove_noncoding),
    )
    return cache_key, genes_tuple


@lru_cache(maxsize=None)
def _tcga_deconvolved_normalized(
    technical_rna_normalize: bool,
    remove_noncoding: bool,
) -> pd.DataFrame:
    """Build + validate the normalized TCGA-deconvolved frame once per worker.

    The normalize -> renormalize -> assert pipeline over the ~640k-row artifact
    costs ~3.5s and is a pure function of the (cached) raw read plus the two
    bool args, so memoize it — callers were re-running it on every call. The
    public wrapper returns a ``.copy()`` to keep the fresh-object contract.
    """
    df = _tcga_deconvolved_expression_cached().copy()
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=("cancer_code",),
        remove_noncoding=remove_noncoding,
    )
    df = _renormalize_long_groups_to_million(
        df,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=("cancer_code",),
    )
    assert_clean_tpm(
        df,
        value_cols=_DECONV_VALUE_COLS,
        label_col="symbol",
        id_col="Ensembl_Gene_ID" if "Ensembl_Gene_ID" in df.columns else None,
        context="tcga_deconvolved_expression",
    )
    return df


def tcga_deconvolved_expression(
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
) -> pd.DataFrame:
    """Per-(gene, TCGA code) tumor-only TPM medians from offline deconv.

    The current bundled artifact includes ``Ensembl_Gene_ID`` when it can be
    recovered unambiguously from the source reference. Historical rows for
    duplicated symbols remain symbol-keyed until the offline generator is rerun
    with the new ID-preserving schema. Trufflepig always exposes the artifact
    on the standard TPM-1e6 footing.
    """
    return _tcga_deconvolved_normalized(
        technical_rna_normalize, remove_noncoding
    ).copy()


@lru_cache(maxsize=None)
def _subtype_deconvolved_normalized(
    technical_rna_normalize: bool,
    remove_noncoding: bool,
) -> pd.DataFrame:
    """Build + validate the normalized subtype-deconvolved frame once per worker.

    Same rationale as :func:`_tcga_deconvolved_normalized`: the pipeline over the
    ~1.05M-row artifact costs ~5s and is pure in (raw read, bool args), so cache
    it instead of recomputing on every call.
    """
    df = _subtype_deconvolved_expression_cached().copy()
    df, _ = _pirlygenes.normalize_expression(
        df,
        label_col="symbol",
        id_col=None,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=_SUBTYPE_GROUP_COLS,
        remove_noncoding=remove_noncoding,
    )
    df = _renormalize_long_groups_to_million(
        df,
        value_cols=_DECONV_VALUE_COLS,
        group_cols=_SUBTYPE_GROUP_COLS,
    )
    assert_clean_tpm(
        df,
        value_cols=_DECONV_VALUE_COLS,
        label_col="symbol",
        id_col=None,
        context="subtype_deconvolved_expression",
    )
    return df


def subtype_deconvolved_expression(
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
) -> pd.DataFrame:
    """Per-(cancer_code, subtype, symbol) tumor-only TPM medians.

    Each (cancer_code, subtype) group is renormalized to the standard
    TPM-1e6 footing — trufflepig does not expose the native bundled scale.
    """
    return _subtype_deconvolved_normalized(
        technical_rna_normalize, remove_noncoding
    ).copy()


@lru_cache(maxsize=1)
def _cancer_reference_manifest_cached() -> pd.DataFrame:
    """Small per-(code, cohort) manifest without loading the 7+ GB summary frame.

    Oncoref owns the empirical reference layer and exposes a gene-independent
    availability table with the fields discovery needs. Pirlygenes'
    public ``available_cancer_expression_references()`` currently derives the same
    rows by materializing the full object-heavy cancer-reference summary; the
    July 2026 macOS panic snapshot measured that path at ~7.4 GB per process.

    Prefer oncoref's public manifest. If that compact path fails, degrade
    directly to registry-declared cohorts. Never invoke pirlygenes' private
    canonical-view loader or the multi-gigabyte legacy availability path.
    """
    availability_verified = False
    try:
        import oncoref

        public_accessor = getattr(
            oncoref, "cancer_reference_expression_availability", None
        )
        if not callable(public_accessor):
            raise AttributeError("oncoref has no reference availability accessor")
        # Keep discovery on the exact view consumed by pirlygenes'
        # cancer_reference_expression() compatibility accessor.  Oncoref's
        # default artifact/pass view can contain cohorts (currently the ESS
        # shards) that the summary_rows_all/all loader cannot return.
        manifest = public_accessor(
            normalize="tpm_clean",
            reference_source="summary_rows_all",
            sample_qc="all",
        )
        manifest = _all_source_reference_availability(
            oncoref,
            public_accessor,
            manifest,
        )
        if "available" in manifest.columns:
            manifest = manifest[manifest["available"].fillna(False).astype(bool)]
        if (
            "n_reference_samples" in manifest.columns
            and "n_samples" in manifest.columns
        ):
            manifest = manifest.copy()
            n_samples = pd.to_numeric(manifest["n_samples"], errors="coerce")
            n_reference_samples = pd.to_numeric(
                manifest["n_reference_samples"], errors="coerce"
            )
            manifest["n_samples"] = n_samples.where(
                n_samples.notna(), n_reference_samples
            )
        if "cancer_code" not in manifest.columns:
            raise ValueError("cancer reference manifest has no cancer_code column")
        availability_verified = True
    except Exception:  # noqa: BLE001 - safe registry fallback is intentional
        manifest = pd.DataFrame(
            columns=[
                "cancer_code",
                "source_cohort",
                "processing_pipeline",
                "n_samples",
            ]
        )

    keep = [
        col
        for col in (
            "cancer_code",
            "source_cohort",
            "processing_pipeline",
            "n_samples",
        )
        if col in manifest.columns
    ]
    if "cancer_code" not in keep:
        raise ValueError("cancer reference manifest has no cancer_code column")
    manifest = manifest[keep].copy()

    # Registry provenance is a safe fallback only for rows that explicitly own
    # their cohort and classify against themselves. Parent-routed subtype rows
    # can carry an expression source/cohort for biological provenance without
    # having a physical clean-TPM artifact of their own (for example the MBL
    # molecular subgroups). Never advertise those as direct references.
    #
    # When oncoref's compact accessor succeeds, it is authoritative for the
    # installed data bundle: registry rows may enrich/deduplicate only identities
    # that accessor already verified. When the accessor itself fails, the
    # explicit own-cohort/self-reference registry contract provides the
    # lightweight failover requested by discovery without loading expression.
    try:
        from .cancer_ontology import cancer_type_registry

        registry = cancer_type_registry()
        code = registry["code"].fillna("").astype(str).str.strip()
        source = registry["source_cohort"].fillna("").astype(str).str.strip()
        expression_source = (
            registry["expression_source"].fillna("").astype(str).str.strip().str.lower()
        )
        reference_source = (
            registry.get("reference_source", pd.Series("", index=registry.index))
            .fillna("")
            .astype(str)
            .str.strip()
            .str.lower()
        )
        classification_reference = (
            registry.get(
                "classification_reference_code",
                pd.Series("", index=registry.index),
            )
            .fillna("")
            .astype(str)
            .str.strip()
        )

        # Older compact availability tables used compatibility aliases as the
        # cohort identity for a few single-source codes (for example MBL_G3 or
        # GSE32662_PRINGLE_2012), while the expression accessor and registry
        # expose the full cohort IDs.  Reconcile only unambiguous one-source
        # codes already verified by availability; never create a row or guess
        # among multi-cohort references.
        if availability_verified and "source_cohort" in manifest.columns:
            registry_sources = pd.DataFrame(
                {"cancer_code": code, "source_cohort": source}
            )[
                ~expression_source.isin({"", "curated", "computed"})
                & source.ne("")
                & ~source.eq("LITERATURE_CURATED")
                & ~source.str.startswith("COMPUTED_")
            ].drop_duplicates()
            manifest_source_counts = manifest.groupby("cancer_code")[
                "source_cohort"
            ].nunique(dropna=True)
            registry_source_counts = registry_sources.groupby("cancer_code")[
                "source_cohort"
            ].nunique(dropna=True)
            unambiguous_codes = set(
                manifest_source_counts[manifest_source_counts.eq(1)].index
            ).intersection(
                registry_source_counts[registry_source_counts.eq(1)].index
            )
            canonical_source = (
                registry_sources[
                    registry_sources["cancer_code"].isin(unambiguous_codes)
                ]
                .set_index("cancer_code")["source_cohort"]
                .to_dict()
            )
            rewrite = manifest["cancer_code"].isin(canonical_source)
            manifest.loc[rewrite, "source_cohort"] = manifest.loc[
                rewrite, "cancer_code"
            ].map(canonical_source)

        own = registry[
            ~expression_source.isin({"", "curated", "computed"})
            & source.ne("")
            & ~source.eq("LITERATURE_CURATED")
            & ~source.str.startswith("COMPUTED_")
            & reference_source.eq("own_cohort")
            & classification_reference.eq(code)
        ][["code", "source_cohort"]].rename(columns={"code": "cancer_code"})
        if availability_verified:
            verified_identities = set()
            if "source_cohort" in manifest.columns:
                verified_identities = set(
                    zip(
                        manifest["cancer_code"]
                        .fillna("")
                        .astype(str)
                        .str.strip(),
                        manifest["source_cohort"]
                        .fillna("")
                        .astype(str)
                        .str.strip(),
                    )
                )
            own_identities = zip(
                own["cancer_code"].fillna("").astype(str).str.strip(),
                own["source_cohort"].fillna("").astype(str).str.strip(),
            )
            own = own[
                [identity in verified_identities for identity in own_identities]
            ]
        manifest = pd.concat([manifest, own], ignore_index=True, sort=False)
    except Exception:  # noqa: BLE001 - availability still works without registry merge
        pass

    # The compact oncoref manifest and the registry intentionally overlap.
    # Their shared identity is (code, cohort), while pipeline/sample metadata
    # exists only on the empirical oncoref row. Prefer the most populated row
    # for each identity instead of full-row deduplication, which retains a
    # second metadata-null registry row and violates the public contract.
    identity_columns = ["cancer_code", "source_cohort"]
    if "source_cohort" not in manifest.columns:
        manifest["source_cohort"] = pd.NA
    for column in identity_columns:
        manifest[column] = manifest[column].astype("string").str.strip()
    metadata_columns = [
        column for column in manifest.columns if column not in identity_columns
    ]
    metadata_completeness = pd.Series(0, index=manifest.index, dtype="int64")
    for column in metadata_columns:
        values = manifest[column]
        populated = values.notna()
        if pd.api.types.is_string_dtype(values.dtype) or values.dtype == object:
            populated &= values.astype("string").str.strip().ne("").fillna(False)
        metadata_completeness += populated.astype("int64")
    manifest = manifest.assign(
        _manifest_metadata_completeness=metadata_completeness,
        _manifest_original_order=range(len(manifest)),
    )
    manifest = (
        manifest.sort_values(
            "_manifest_metadata_completeness",
            ascending=False,
            kind="stable",
        )
        .drop_duplicates(subset=identity_columns, keep="first")
        .sort_values("_manifest_original_order", kind="stable")
        .drop(
            columns=[
                "_manifest_metadata_completeness",
                "_manifest_original_order",
            ]
        )
        .reset_index(drop=True)
    )
    return manifest


def cancer_reference_manifest() -> pd.DataFrame:
    """Return one lightweight provenance row per observed reference cohort."""
    return _cancer_reference_manifest_cached().copy()


def cancer_reference_expression(
    cancer_types=None,
    genes=None,
    normalize: str | list[str] | tuple[str, ...] = "tpm_clean",
    *,
    format: str = "long",
    include_provenance: bool = True,
) -> pd.DataFrame:
    """Observed non-TCGA tumor expression references from pirlygenes.

    This is distinct from trufflepig's deconvolved tumor-cell references.
    The default view is observed cohort clean TPM, source-preserving, and
    suitable for expression matching or fallback priors when no deconvolved
    tumor reference exists.
    """
    accessor = getattr(_pirlygenes, "cancer_reference_expression", None)
    if accessor is None:
        if format == "long":
            return pd.DataFrame(columns=_CANCER_REFERENCE_EMPTY_COLUMNS)
        return pd.DataFrame(columns=["Ensembl_Gene_ID", "Symbol"])

    df = accessor(
        cancer_types=cancer_types,
        genes=genes,
        normalize=normalize,
        format=format,
        include_provenance=include_provenance,
    ).copy()
    modes = (
        {str(mode).lower() for mode in normalize}
        if isinstance(normalize, (list, tuple, set))
        else {str(normalize).lower()}
    )
    clean_requested = bool(modes & {"tpm_clean", "clean_tpm"})
    if clean_requested and not df.empty:
        if format == "long":
            clean_rows = (
                df["normalization"].astype(str).str.lower().eq("tpm_clean")
                if "normalization" in df.columns
                else pd.Series(True, index=df.index)
            )
            value_cols = [col for col in ("expression", "q1", "q3") if col in df.columns]
            assert_clean_tpm(
                df.loc[clean_rows],
                value_cols=value_cols,
                context="cancer_reference_expression",
                technical_fraction=_CLEAN_TPM_V4_TECHNICAL_FRACTION,
            )
        else:
            value_cols = [col for col in df.columns if str(col).endswith("_TPM_clean")]
            assert_clean_tpm(
                df,
                value_cols=value_cols,
                context="cancer_reference_expression",
                technical_fraction=_CLEAN_TPM_V4_TECHNICAL_FRACTION,
            )
    return df


def pan_cancer_expression(
    genes=None,
    normalize=None,
    log_transform: bool = False,
    technical_rna_normalize: bool = False,
    remove_noncoding: bool = False,
) -> pd.DataFrame:
    """Expression across 50 normal tissues (nTPM) and 33 TCGA cancer types.

    Wraps :func:`pirlygenes.pan_cancer_expression` with trufflepig's
    TPM analysis view: raw TCGA/HPA TPM columns are retained only as
    explicit ``*_TPM_raw`` / ``*_nTPM_raw`` companions, clean columns are
    retained as ``*_TPM_clean`` / ``*_nTPM_clean``, and the analysis-facing
    ``*_TPM`` / ``*_nTPM`` aliases always point at the clean values.
    """
    cache_key, genes_tuple = _pan_cancer_cache_key(
        genes,
        normalize,
        log_transform,
        technical_rna_normalize,
        remove_noncoding,
    )
    cached = _PAN_CANCER_CACHE.get(cache_key)
    if cached is not None:
        return cached.copy()

    df = _load_pan_cancer_from_pirlygenes(
        genes_tuple=genes_tuple,
        remove_noncoding=remove_noncoding,
    )
    df = _standardize_pan_cancer_columns(df)
    # Collapse byte-identical-protein loci to the proteoform key space (SUM in
    # linear TPM/nTPM space — must precede any log/percentile transform). See
    # common.collapse_proteoform_loci. Sample conform + panels fold to match.
    from trufflepig.common import collapse_proteoform_loci

    wide_value_cols = _all_wide_tpm_value_cols(df)
    if wide_value_cols:
        df = collapse_proteoform_loci(df, value_cols=wide_value_cols)
    df = _apply_trufflepig_pan_normalize(df, normalize, log_transform)
    clean_companion_cols = _clean_companion_value_cols(df)
    if not clean_companion_cols:
        raise ValueError(
            "pirlygenes pan_cancer_expression did not provide clean TPM columns; "
            "trufflepig requires *_TPM_clean/*_nTPM_clean for analysis"
        )
    assert_clean_tpm(
        df,
        value_cols=clean_companion_cols,
        context="pan_cancer_expression",
    )
    _PAN_CANCER_CACHE[cache_key] = df
    return df.copy()


def cancer_types() -> list[str]:
    """Return the list of available TCGA cancer type codes (``<CODE>_TPM`` columns)."""
    df = pan_cancer_expression()
    return sorted(c.removesuffix("_TPM") for c in df.columns if c.endswith("_TPM"))


def cancer_expression(cancer_type, genes=None) -> pd.DataFrame:
    """Expression for a single cancer type as a simple gene-level DataFrame.

    Columns: ``Ensembl_Gene_ID``, ``Symbol``, ``expression``
    (housekeeping-normalized, technical-RNA-normalized).
    """
    from trufflepig.cancer_ontology import resolve_cancer_type

    code = resolve_cancer_type(cancer_type)
    df = pan_cancer_expression(
        genes=genes,
        normalize="housekeeping",
        technical_rna_normalize=True,
    )
    col = f"{code}_TPM"
    return df[["Ensembl_Gene_ID", "Symbol", col]].rename(columns={col: "expression"})


def cancer_enriched_genes(
    cancer_type,
    min_fold: float = 3.0,
    min_expression: float = 0.01,
) -> pd.DataFrame:
    """Genes enriched in one cancer type vs the median of all others."""
    from trufflepig.cancer_ontology import resolve_cancer_type

    code = resolve_cancer_type(cancer_type)
    df = pan_cancer_expression(normalize="housekeeping", technical_rna_normalize=True)
    target_col = f"{code}_TPM"
    if target_col not in df.columns:
        raise ValueError(
            f"Cancer type {cancer_type!r} -> {code!r} not in pan-cancer reference"
        )
    other_cols = [c for c in df.columns if c.endswith("_TPM") and c != target_col]
    target = df[target_col].astype(float)
    other_median = df[other_cols].astype(float).median(axis=1)
    fold = target / other_median.replace(0, float("nan"))
    keep = (fold >= min_fold) & (target >= min_expression)
    out = df.loc[keep, ["Ensembl_Gene_ID", "Symbol", target_col]].copy()
    out = out.rename(columns={target_col: "expression"})
    out["fold_over_others"] = fold[keep].values
    return out.sort_values("fold_over_others", ascending=False)


def top_enriched_per_cancer_type(
    top_n: int = 20,
    min_fold: float = 3.0,
    min_expression: float = 0.01,
) -> dict[str, pd.DataFrame]:
    """Top-N enriched genes per TCGA code (dict keyed by code)."""
    out: dict[str, pd.DataFrame] = {}
    for code in cancer_types():
        enriched = cancer_enriched_genes(
            code,
            min_fold=min_fold,
            min_expression=min_expression,
        )
        out[code] = enriched.head(top_n)
    return out


def tumor_up_vs_matched_normal(cancer_code: str | None = None) -> pd.DataFrame:
    """Solid-tumor genes dramatically up vs matched normal tissue."""
    return _filter_cancer_code(_tumor_up_vs_matched_normal_cached().copy(), cancer_code)


def heme_tumor_up_vs_matched_normal(cancer_code: str | None = None) -> pd.DataFrame:
    """Heme analogue of :func:`tumor_up_vs_matched_normal`."""
    return _filter_cancer_code(
        _heme_tumor_up_vs_matched_normal_cached().copy(),
        cancer_code,
    )


def hpa_cell_type_expression() -> pd.DataFrame:
    """Clean per-(gene, cell-type) nTPM from the HPA single-cell consensus."""
    return _hpa_cell_type_expression_cached().copy()


def estimate_signatures() -> pd.DataFrame:
    """ESTIMATE stromal / immune signature panels (Yoshihara 2013)."""
    return _pirlygenes.estimate_signatures()
